<?php

return [
    'version' => '2026-06-19-prompt-v2',

    'pillars' => [
        ['slug' => 'znaki-ostrzegawcze', 'title' => 'Znaki ostrzegawcze', 'topic_key' => 'warning_signs'],
        ['slug' => 'znaki-zakazu-i-nakazu', 'title' => 'Znaki zakazu i nakazu', 'topic_key' => 'prohibition_and_mandatory_signs'],
        ['slug' => 'znaki-informacyjne-i-tabliczki', 'title' => 'Znaki informacyjne, kierunku i tabliczki', 'topic_key' => 'informational_direction_and_supplementary_signs'],
        ['slug' => 'oznakowanie-poziome', 'title' => 'Oznakowanie poziome drogi', 'topic_key' => 'road_markings'],
        ['slug' => 'sygnaly-swietlne-i-kierujacy-ruchem', 'title' => 'Sygnały świetlne i osoby kierujące ruchem', 'topic_key' => 'traffic_lights_and_controller_signals', 'existing_article_slug' => 'sygnalizacja-i-osoby-kierujace-ruchem'],
        ['slug' => 'swiatla-i-sygnaly-pojazdu', 'title' => 'Światła zewnętrzne i sygnały pojazdu', 'topic_key' => 'vehicle_lights_and_signals'],
        ['slug' => 'wlaczanie-sie-i-skrzyzowania-rownorzedne', 'title' => 'Włączanie się do ruchu i skrzyżowania równorzędne', 'topic_key' => 'joining_traffic_and_equal_intersections'],
        ['slug' => 'pierwszenstwo-na-skrzyzowaniach', 'title' => 'Pierwszeństwo na skrzyżowaniach ze znakami', 'topic_key' => 'intersections_with_priority_signs', 'existing_article_slug' => 'pierwszenstwo-przejazdu'],
        ['slug' => 'skrzyzowania-z-sygnalizacja', 'title' => 'Skrzyżowania z sygnalizacją świetlną', 'topic_key' => 'intersections_with_traffic_lights'],
        ['slug' => 'przejscia-przystanki-i-kierujacy-ruchem', 'title' => 'Przejścia, przystanki i kierujący ruchem', 'topic_key' => 'controlled_crossings_and_public_transport_stops'],
        ['slug' => 'przejazdy-kolejowe-i-tramwajowe', 'title' => 'Przejazdy kolejowe i tramwajowe', 'topic_key' => 'rail_and_tram_crossings'],
        ['slug' => 'pozycja-pojazdu-zatrzymanie-i-postoj', 'title' => 'Pozycja pojazdu, zatrzymanie i postój', 'topic_key' => 'road_position_entry_exit_stopping'],
        ['slug' => 'zmiana-pasa-skret-i-zawracanie', 'title' => 'Zmiana pasa, skręt i zawracanie', 'topic_key' => 'lane_change_and_turning', 'existing_article_slug' => 'zmiana-kierunku-i-pasa-ruchu'],
        ['slug' => 'wyprzedzanie', 'title' => 'Wyprzedzanie', 'topic_key' => 'overtaking', 'existing_article_slug' => 'wyprzedzanie'],
        ['slug' => 'omijanie-wymijanie-i-cofanie', 'title' => 'Omijanie, wymijanie i cofanie', 'topic_key' => 'passing_reversing', 'existing_article_slug' => 'wymijanie-omijanie-cofanie'],
        ['slug' => 'piesi-i-osoby-o-ograniczonej-mobilnosci', 'title' => 'Piesi i osoby o ograniczonej mobilności', 'topic_key' => 'behaviour_towards_pedestrians_and_reduced_mobility', 'existing_article_slug' => 'piesi-i-przejscia'],
        ['slug' => 'rowerzysci-dzieci-hulajnogi-i-uto', 'title' => 'Rowerzyści, dzieci, hulajnogi i UTO', 'topic_key' => 'behaviour_towards_cyclists_and_children'],
        ['slug' => 'szczegolna-ostroznosc-i-zabezpieczenie-pojazdu', 'title' => 'Szczególna ostrożność i zabezpieczenie pojazdu', 'topic_key' => 'special_caution_exiting_and_securing_vehicle'],
        ['slug' => 'awaria-wypadek-i-pierwsza-pomoc', 'title' => 'Awaria, wypadek i pierwsza pomoc', 'topic_key' => 'breakdown_accident_and_first_aid'],
        ['slug' => 'alkohol-leki-zmeczenie-i-czas-reakcji', 'title' => 'Alkohol, leki, zmęczenie i czas reakcji', 'topic_key' => 'perception_decision_alcohol_fatigue'],
        ['slug' => 'dopuszczalne-predkosci', 'title' => 'Dopuszczalne prędkości pojazdów', 'topic_key' => 'speed_limits', 'existing_article_slug' => 'predkosc-odstep-i-hamowanie'],
        ['slug' => 'odstep-droga-hamowania-i-zatrzymania', 'title' => 'Odstęp, droga hamowania i zatrzymania', 'topic_key' => 'distances_and_braking', 'existing_article_slug' => 'predkosc-odstep-i-hamowanie'],
        ['slug' => 'technika-kierowania-pojazdem', 'title' => 'Technika kierowania pojazdem', 'topic_key' => 'driving_technique'],
        ['slug' => 'pasy-foteliki-kaski-i-wyposazenie', 'title' => 'Pasy, foteliki, kaski i wyposażenie bezpieczeństwa', 'topic_key' => 'safety_equipment_and_restraints'],
        ['slug' => 'ladunek-i-bezpieczenstwo-pasazerow', 'title' => 'Ładunek i bezpieczeństwo przewożonych osób', 'topic_key' => 'vehicle_load_and_passenger_safety'],
        ['slug' => 'pogoda-warunki-drogowe-i-ryzyko', 'title' => 'Pogoda, warunki drogowe i czynniki ryzyka', 'topic_key' => 'risk_factors_conditions_and_weather'],
        ['slug' => 'pole-widzenia-lusterka-i-martwe-pole', 'title' => 'Pole widzenia, lusterka i martwe pole', 'topic_key' => 'driver_field_of_view'],
        ['slug' => 'dokumenty-uprawnienia-i-ubezpieczenie', 'title' => 'Dokumenty, uprawnienia i ubezpieczenie', 'topic_key' => 'owner_obligations_insurance_documents'],
        ['slug' => 'stan-techniczny-i-uklady-bezpieczenstwa', 'title' => 'Stan techniczny i układy bezpieczeństwa pojazdu', 'topic_key' => 'mechanical_aspects_of_safety'],
        ['slug' => 'pierwsza-pomoc-i-akcje-ratunkowe', 'title' => 'Pierwsza pomoc i akcje ratunkowe', 'topic_key' => 'rescue_actions'],
        ['slug' => 'jazda-z-przyczepa', 'title' => 'Jazda z przyczepą', 'topic_key' => 'driving_with_trailer'],
    ],

    'focused' => [
        [
            'slug' => 'pojazd-uprzywilejowany',
            'title' => 'Pojazd uprzywilejowany i tworzenie korytarza życia',
            'prompt_any' => ['pojazd uprzywilejowan', 'korytarz zycia'],
        ],
        [
            'slug' => 'autobus-wlaczajacy-sie-z-przystanku',
            'title' => 'Autobus wyjeżdżający z przystanku',
            'topic_keys' => ['controlled_crossings_and_public_transport_stops', 'joining_traffic_and_equal_intersections'],
            'prompt_any' => ['kierujacemu autobusem', 'autobusowi wlaczenie sie', 'autobusem wlaczenie sie do ruchu'],
            'existing_article_slug' => 'autobus-wyjezdzajacy-z-przystanku',
        ],
        [
            'slug' => 'tramwaj-na-przystanku-bez-wysepki',
            'title' => 'Tramwaj na przystanku bez wysepki',
            'topic_keys' => ['controlled_crossings_and_public_transport_stops'],
            'prompt_any' => ['przystanku tramwaj', 'tramwaj stojacego na przystanku', 'tramwaju stojacego na przystanku'],
            'existing_article_slug' => 'tramwaje-i-przystanki',
        ],
        [
            'slug' => 'zielona-strzalka-warunkowa',
            'title' => 'Zielona strzałka warunkowa',
            'topic_keys' => ['traffic_lights_and_controller_signals', 'intersections_with_traffic_lights'],
            'prompt_any' => ['sygnal w ksztalcie zielonej strzalki', 'zielona strzalka', 'skrecic w prawo bez zatrzymania'],
        ],
        [
            'slug' => 'sygnal-zolty-i-zolty-migajacy',
            'title' => 'Sygnał żółty i żółty migający',
            'topic_keys' => ['traffic_lights_and_controller_signals', 'intersections_with_traffic_lights'],
            'prompt_any' => ['sygnal zolty', 'zolty migajacy', 'migajacy sygnal zolty'],
        ],
        [
            'slug' => 'polecenia-policjanta-i-kierujacego-ruchem',
            'title' => 'Polecenia policjanta i osoby kierującej ruchem',
            'topic_keys' => ['traffic_lights_and_controller_signals', 'controlled_crossings_and_public_transport_stops'],
            'prompt_any' => ['policjant', 'kierujacy ruchem', 'osoby kierujacej ruchem'],
            'existing_article_slug' => 'sygnalizacja-i-osoby-kierujace-ruchem',
        ],
        [
            'slug' => 'swiatla-drogowe-i-oslepianie',
            'title' => 'Światła drogowe i zakaz oślepiania',
            'topic_keys' => ['vehicle_lights_and_signals'],
            'prompt_any' => ['swiatel drogowych', 'swiatla drogowe', 'zmienic swiatla drogowe na swiatla mijania'],
            'existing_article_slug' => 'swiatla-drogowe-i-oslepianie',
        ],
        [
            'slug' => 'swiatla-przeciwmglowe',
            'title' => 'Światła przeciwmgłowe',
            'topic_keys' => ['vehicle_lights_and_signals', 'risk_factors_conditions_and_weather'],
            'prompt_any' => ['przeciwmglow'],
            'existing_article_slug' => 'swiatla-przeciwmglowe',
        ],
        [
            'slug' => 'swiatla-do-jazdy-dziennej-i-mijania',
            'title' => 'Światła do jazdy dziennej i światła mijania',
            'topic_keys' => ['vehicle_lights_and_signals'],
            'prompt_any' => ['swiatel do jazdy dziennej', 'swiatla do jazdy dziennej', 'swiatel mijania', 'swiatla mijania'],
            'existing_article_slug' => 'swiatla-do-jazdy-dziennej-i-mijania',
        ],
        [
            'slug' => 'sygnal-dzwiekowy',
            'title' => 'Kiedy wolno używać sygnału dźwiękowego',
            'prompt_any' => ['sygnalu dzwiekowego', 'sygnal dzwiekowy'],
            'existing_article_slug' => 'sygnal-dzwiekowy',
        ],
        [
            'slug' => 'wyjazd-z-posesji-parkingu-i-strefy',
            'title' => 'Wyjazd z posesji, parkingu i strefy zamieszkania',
            'topic_keys' => ['joining_traffic_and_equal_intersections'],
            'prompt_any' => ['wyjezdzajac z parkingu', 'wyjazd z parkingu', 'wyjezdzajac z posesji', 'wyjazd z posesji', 'wyjezdzajac ze strefy zamieszkania'],
            'existing_article_slug' => 'wlaczanie-sie-do-ruchu',
        ],
        [
            'slug' => 'skrzyzowanie-rownorzedne-i-zasada-prawej-reki',
            'title' => 'Skrzyżowanie równorzędne i zasada prawej ręki',
            'topic_keys' => ['joining_traffic_and_equal_intersections'],
            'prompt_any' => ['skrzyzowaniu rownorzednym', 'skrzyzowanie rownorzedne', 'nadjezdzajacym z prawej strony'],
        ],
        [
            'slug' => 'skret-w-lewo-i-pojazd-z-naprzeciwka',
            'title' => 'Skręt w lewo i pojazd jadący z naprzeciwka',
            'topic_keys' => ['intersections_with_priority_signs', 'intersections_with_traffic_lights', 'joining_traffic_and_equal_intersections'],
            'prompt_all' => ['skrec', 'w lewo'],
            'prompt_any' => ['z przeciwka', 'z naprzeciwka', 'jadacym na wprost'],
            'existing_article_slug' => 'pierwszenstwo-przejazdu',
        ],
        [
            'slug' => 'rondo-i-ruch-okrezny',
            'title' => 'Rondo i skrzyżowanie o ruchu okrężnym',
            'topic_keys' => ['intersections_with_priority_signs', 'lane_change_and_turning', 'warning_signs'],
            'prompt_any' => ['ruchu okreznym', 'rondo'],
        ],
        [
            'slug' => 'zablokowane-skrzyzowanie',
            'title' => 'Zakaz wjazdu na zablokowane skrzyżowanie',
            'topic_keys' => ['intersections_with_traffic_lights', 'road_position_entry_exit_stopping'],
            'prompt_any' => ['nie bedziesz mogl opuscic skrzyzowania', 'zablokowac skrzyzowanie', 'tamowanie ruchu na skrzyzowaniu'],
        ],
        [
            'slug' => 'rogatki-i-sygnaly-na-przejezdzie-kolejowym',
            'title' => 'Rogatki i sygnały na przejeździe kolejowym',
            'topic_keys' => ['rail_and_tram_crossings'],
            'prompt_any' => ['rogatk', 'zapor', 'sygnal czerwony na przejezdzie', 'pracownika kolejowego'],
            'existing_article_slug' => 'rogatki-i-sygnaly-na-przejezdzie-kolejowym',
        ],
        [
            'slug' => 'wjazd-na-przejazd-kolejowy',
            'title' => 'Kiedy nie wolno wjechać na przejazd kolejowy',
            'topic_keys' => ['rail_and_tram_crossings'],
            'prompt_any' => ['wjechac na przejazd kolejowy', 'wjechac na przejazd', 'przejechac przez przejazd kolejowy'],
            'existing_article_slug' => 'wjazd-na-przejazd-kolejowy',
        ],
        [
            'slug' => 'parkowanie-na-chodniku',
            'title' => 'Zatrzymanie i parkowanie na chodniku',
            'topic_keys' => ['road_position_entry_exit_stopping'],
            'prompt_any' => ['zaparkowac pojazd na chodniku', 'parkowanie na chodniku', 'zatrzymac pojazd na chodniku'],
            'existing_article_slug' => 'zatrzymanie-i-postoj',
        ],
        [
            'slug' => 'zakazy-zatrzymania-przy-przejsciu-skrzyzowaniu-i-przystanku',
            'title' => 'Miejsca, w których zatrzymanie lub postój są zabronione',
            'topic_keys' => ['road_position_entry_exit_stopping', 'prohibition_and_mandatory_signs'],
            'prompt_any' => ['zatrzymac pojazd', 'zaparkowac pojazd', 'zakaz zatrzymywania'],
            'prompt_any_context' => ['przejsc', 'skrzyz', 'przystank', 'wiadukt', 'tunel', 'most'],
            'prompt_none' => ['obowiazek kazdorazowo zatrzymac', 'obowiazek zatrzymac pojazd przed wjazdem'],
            'existing_article_slug' => 'zatrzymanie-i-postoj',
        ],
        [
            'slug' => 'kierunkowskaz-przy-zmianie-pasa-i-skrecie',
            'title' => 'Kierunkowskaz przy zmianie pasa i skręcie',
            'topic_keys' => ['lane_change_and_turning', 'traffic_lights_and_controller_signals'],
            'prompt_any' => ['kierunkowskaz', 'sygnalizowac zamiar', 'sygnalizowania zamiaru'],
            'existing_article_slug' => 'zmiana-kierunku-i-pasa-ruchu',
        ],
        [
            'slug' => 'pierwszenstwo-przy-zmianie-pasa',
            'title' => 'Pierwszeństwo przy zmianie pasa ruchu',
            'topic_keys' => ['lane_change_and_turning'],
            'prompt_all' => ['zmien', 'pas ruchu'],
            'prompt_any' => ['pierwszenstw', 'ustapic'],
            'existing_article_slug' => 'zmiana-kierunku-i-pasa-ruchu',
        ],
        [
            'slug' => 'zawracanie',
            'title' => 'Zawracanie: dozwolone miejsca, pas ruchu i sygnalizacja',
            'topic_keys' => ['lane_change_and_turning', 'road_markings', 'prohibition_and_mandatory_signs', 'intersections_with_traffic_lights'],
            'prompt_any' => ['zawroc', 'zawrac'],
            'existing_article_slug' => 'zawracanie',
        ],
        [
            'slug' => 'wyprzedzanie-rowerzysty-i-odstep-jeden-metr',
            'title' => 'Wyprzedzanie rowerzysty i odstęp co najmniej 1 m',
            'prompt_any' => ['wyprzedzania rowerzyst', 'wyprzedzic rowerzyst', 'od rowerzysty podczas wyprzedzania'],
            'existing_article_slug' => 'wyprzedzanie',
        ],
        [
            'slug' => 'zakazy-wyprzedzania',
            'title' => 'Zakazy wyprzedzania na skrzyżowaniach, przejściach i przejazdach',
            'topic_keys' => ['overtaking', 'prohibition_and_mandatory_signs', 'road_markings'],
            'prompt_any' => ['zakaz wyprzedzania', 'wolno ci wyprzedz', 'mozesz wyprzedz', 'wyprzedzanie jest zabronione'],
            'prompt_any_context' => ['skrzyz', 'przejsc', 'przejazd kolej', 'linia ciagla', 'zakret'],
            'existing_article_slug' => 'wyprzedzanie',
        ],
        [
            'slug' => 'wyprzedzanie-z-prawej-strony',
            'title' => 'Wyprzedzanie z prawej strony',
            'topic_keys' => ['overtaking'],
            'prompt_any' => ['wyprzedzania z prawej strony', 'wyprzedzic z prawej strony', 'z jego prawej strony'],
            'existing_article_slug' => 'wyprzedzanie',
        ],
        [
            'slug' => 'cofanie-i-zakazy-cofania',
            'title' => 'Cofanie i miejsca, w których jest zabronione',
            'topic_keys' => ['passing_reversing'],
            'prompt_any' => ['cofac', 'cofania', 'cofanie'],
            'existing_article_slug' => 'wymijanie-omijanie-cofanie',
        ],
        [
            'slug' => 'omijanie-zatrzymanego-pojazdu',
            'title' => 'Omijanie zatrzymanego pojazdu',
            'topic_keys' => ['passing_reversing'],
            'prompt_any' => ['omijan', 'manewr omijania'],
            'existing_article_slug' => 'wymijanie-omijanie-cofanie',
        ],
        [
            'slug' => 'pieszy-na-przejsciu-i-wchodzacy-na-przejscie',
            'title' => 'Pieszy na przejściu i wchodzący na przejście',
            'topic_keys' => ['behaviour_towards_pedestrians_and_reduced_mobility', 'controlled_crossings_and_public_transport_stops'],
            'prompt_any' => ['przejscia dla pieszych', 'przejscie dla pieszych'],
            'existing_article_slug' => 'piesi-i-przejscia',
        ],
        [
            'slug' => 'skret-a-pierwszenstwo-pieszego',
            'title' => 'Skręt w drogę poprzeczną a pierwszeństwo pieszego',
            'topic_keys' => ['behaviour_towards_pedestrians_and_reduced_mobility'],
            'prompt_all' => ['skrec', 'piesz'],
            'prompt_any' => ['ustapic pierwszenstwa', 'pierwszenstwo przed pieszym'],
            'existing_article_slug' => 'piesi-i-przejscia',
        ],
        [
            'slug' => 'przejazd-przez-chodnik-droge-dla-pieszych-i-brame',
            'title' => 'Przejazd przez chodnik, drogę dla pieszych i wjazd do bramy',
            'topic_keys' => ['behaviour_towards_pedestrians_and_reduced_mobility', 'joining_traffic_and_equal_intersections'],
            'prompt_any' => ['przejechac przez chodnik', 'przejezdzajac przez chodnik', 'wjazd do bramy', 'skrecic do bramy', 'droge dla pieszych'],
            'existing_article_slug' => 'piesi-i-przejscia',
        ],
        [
            'slug' => 'hulajnoga-elektryczna-i-uto',
            'title' => 'Hulajnoga elektryczna i urządzenia transportu osobistego',
            'topic_keys' => ['behaviour_towards_cyclists_and_children'],
            'prompt_any' => ['hulajnoga elektrycz', 'urzadzeniem transportu osobistego', 'urzadzenia transportu osobistego'],
        ],
        [
            'slug' => 'telefon-podczas-kierowania',
            'title' => 'Telefon podczas kierowania pojazdem, rowerem lub hulajnogą',
            'prompt_any' => ['telefon', 'sluchawki lub mikrofonu', 'sluchawke lub mikrofon'],
            'prompt_any_context' => ['podczas kierowania', 'kierujac pojazdem', 'kierowania hulajnoga', 'kierujac tramwajem'],
            'existing_article_slug' => 'telefon-podczas-kierowania',
        ],
        [
            'slug' => 'alkohol-i-srodki-dzialajace-podobnie',
            'title' => 'Alkohol i środki działające podobnie',
            'topic_keys' => ['perception_decision_alcohol_fatigue'],
            'prompt_any' => ['alkohol', 'nietrzezw', 'stanie po uzyciu'],
        ],
        [
            'slug' => 'leki-zmeczenie-i-sennosc',
            'title' => 'Leki, zmęczenie i senność za kierownicą',
            'topic_keys' => ['perception_decision_alcohol_fatigue'],
            'prompt_any' => ['lekow', 'leki ', 'zmeczen', 'sennosc', 'nasennych'],
        ],
        [
            'slug' => 'predkosc-w-obszarze-zabudowanym-i-strefach',
            'title' => 'Prędkość w obszarze zabudowanym, strefie zamieszkania i strefie ruchu',
            'topic_keys' => ['speed_limits', 'informational_direction_and_supplementary_signs'],
            'prompt_any' => ['obszarze zabudowanym', 'strefie zamieszkania', 'strefy zamieszkania', 'strefie ruchu'],
            'prompt_any_context' => ['predkosc', 'km h', 'jechac'],
            'existing_article_slug' => 'predkosc-odstep-i-hamowanie',
        ],
        [
            'slug' => 'predkosc-na-autostradzie-i-drodze-ekspresowej',
            'title' => 'Prędkość na autostradzie i drodze ekspresowej',
            'topic_keys' => ['speed_limits', 'informational_direction_and_supplementary_signs'],
            'prompt_any' => ['na autostradzie', 'autostrade', 'drodze ekspresowej'],
            'prompt_any_context' => ['predkosc', 'km h'],
            'existing_article_slug' => 'predkosc-odstep-i-hamowanie',
        ],
        [
            'slug' => 'minimalny-odstep-w-tunelu',
            'title' => 'Minimalny odstęp w tunelu',
            'topic_keys' => ['distances_and_braking'],
            'prompt_all' => ['tunel', 'odstep'],
            'existing_article_slug' => 'predkosc-odstep-i-hamowanie',
        ],
        [
            'slug' => 'droga-hamowania-a-predkosc-i-nawierzchnia',
            'title' => 'Droga hamowania a prędkość i stan nawierzchni',
            'topic_keys' => ['distances_and_braking', 'risk_factors_conditions_and_weather'],
            'prompt_any' => ['droga hamowania', 'drogi hamowania', 'droge hamowania'],
            'existing_article_slug' => 'predkosc-odstep-i-hamowanie',
        ],
        [
            'slug' => 'pasy-bezpieczenstwa',
            'title' => 'Pasy bezpieczeństwa: obowiązek i wyjątki',
            'topic_keys' => ['safety_equipment_and_restraints', 'vehicle_load_and_passenger_safety'],
            'prompt_any' => ['pasow bezpieczenstwa', 'pasy bezpieczenstwa'],
            'existing_article_slug' => 'pasy-bezpieczenstwa',
        ],
        [
            'slug' => 'foteliki-i-przewoz-dzieci',
            'title' => 'Foteliki i przewóz dzieci w samochodzie',
            'topic_keys' => ['safety_equipment_and_restraints', 'vehicle_load_and_passenger_safety'],
            'prompt_any' => ['fotelik', 'przewozisz dziecko', 'przewozenie dziecka', 'dziecka o wzroscie'],
            'existing_article_slug' => 'foteliki-i-przewoz-dzieci',
        ],
        [
            'slug' => 'kask-i-odziez-ochronna',
            'title' => 'Kask i odzież ochronna motocyklisty oraz motorowerzysty',
            'topic_keys' => ['safety_equipment_and_restraints'],
            'prompt_any' => ['kasku ochronnego', 'odziez ochron', 'stroju ochron'],
        ],
        [
            'slug' => 'gasnica-trojkat-i-obowiazkowe-wyposazenie',
            'title' => 'Gaśnica, trójkąt i obowiązkowe wyposażenie pojazdu',
            'topic_keys' => ['safety_equipment_and_restraints', 'breakdown_accident_and_first_aid'],
            'prompt_any' => ['gasnic', 'trojkat ostrzegawczy', 'obowiazkowym wyposazeniem'],
            'existing_article_slug' => 'gasnica-trojkat-i-obowiazkowe-wyposazenie',
        ],
        [
            'slug' => 'zabezpieczenie-ladunku-i-wymiary',
            'title' => 'Zabezpieczenie ładunku, jego wymiary i oznakowanie',
            'topic_keys' => ['vehicle_load_and_passenger_safety', 'driving_with_trailer'],
            'prompt_any' => ['ladunek', 'ladunku', 'ladownosc'],
            'existing_article_slug' => 'zabezpieczenie-ladunku-i-wymiary',
        ],
        [
            'slug' => 'mgla-i-ograniczona-widocznosc',
            'title' => 'Jazda we mgle i przy ograniczonej widoczności',
            'topic_keys' => ['risk_factors_conditions_and_weather', 'vehicle_lights_and_signals'],
            'prompt_any' => ['mgle', 'mgla', 'ograniczonej widocznosci'],
        ],
        [
            'slug' => 'snieg-lod-i-poslizg',
            'title' => 'Śnieg, lód, przyczepność i poślizg',
            'topic_keys' => ['risk_factors_conditions_and_weather', 'distances_and_braking'],
            'prompt_any' => ['snieg', 'oblodz', 'poslizg', 'slisk'],
        ],
        [
            'slug' => 'lusterka-i-martwe-pole',
            'title' => 'Ustawienie lusterek i martwe pole',
            'topic_keys' => ['driver_field_of_view'],
            'prompt_any' => ['luster', 'martwe pole'],
        ],
        [
            'slug' => 'kategorie-prawa-jazdy-i-uprawnienia',
            'title' => 'Kategorie prawa jazdy i zakres uprawnień',
            'topic_keys' => ['owner_obligations_insurance_documents'],
            'prompt_any' => ['prawo jazdy kategorii', 'kategorie prawa jazdy', 'posiadajac prawo jazdy'],
            'existing_article_slug' => 'kategorie-prawa-jazdy-i-uprawnienia',
        ],
        [
            'slug' => 'czas-pracy-przerwy-i-odpoczynek-kierowcy',
            'title' => 'Czas pracy, przerwy i odpoczynek kierowcy zawodowego',
            'topic_keys' => ['owner_obligations_insurance_documents'],
            'prompt_any' => ['czas prowadzenia', 'dziennego odpoczynku', 'okres odpoczynku', 'przerwy w prowadzeniu'],
        ],
        [
            'slug' => 'dokumenty-podczas-kontroli-drogowej',
            'title' => 'Dokumenty podczas kontroli drogowej',
            'prompt_any' => ['dokumenty masz obowiazek miec przy sobie', 'okazywac na zadanie uprawnionego organu'],
            'existing_article_slug' => 'dokumenty-podczas-kontroli-drogowej',
        ],
        [
            'slug' => 'opony-bieznik-i-cisnienie',
            'title' => 'Opony, bieżnik i ciśnienie',
            'topic_keys' => ['mechanical_aspects_of_safety', 'safety_equipment_and_restraints'],
            'prompt_any' => ['opon', 'bieznik', 'cisnieni'],
            'existing_article_slug' => 'opony-bieznik-i-cisnienie',
        ],
        [
            'slug' => 'abs-esp-asr-i-systemy-bezpieczenstwa',
            'title' => 'ABS, ESP, ASR i elektroniczne systemy bezpieczeństwa',
            'topic_keys' => ['mechanical_aspects_of_safety', 'distances_and_braking', 'risk_factors_conditions_and_weather'],
            'prompt_any' => ['uklad abs', 'ukladu abs', 'system abs', 'uklad asr', 'ukladu asr', 'system asr', 'tzw asr', 'uklad esp', 'ukladu esp', 'system esp', 'tzw esp'],
        ],
        [
            'slug' => 'obowiazki-uczestnika-wypadku',
            'title' => 'Obowiązki uczestnika wypadku drogowego',
            'topic_keys' => ['breakdown_accident_and_first_aid', 'rescue_actions'],
            'prompt_any' => ['uczestnicz w wypadku', 'uczestnikiem wypadku', 'uczestnik wypadku'],
            'existing_article_slug' => 'obowiazki-uczestnika-wypadku',
        ],
        [
            'slug' => 'resuscytacja-aed-i-brak-oddechu',
            'title' => 'Resuscytacja, AED i brak oddechu',
            'topic_keys' => ['rescue_actions', 'breakdown_accident_and_first_aid'],
            'prompt_any' => ['resuscyt', 'aed', 'brak oddechu', 'nie oddycha'],
        ],
        [
            'slug' => 'krwotok-rany-i-zlamania',
            'title' => 'Krwotok, rany i złamania: pierwsza pomoc',
            'topic_keys' => ['rescue_actions', 'breakdown_accident_and_first_aid'],
            'prompt_any' => ['krwotok', 'krwawiac', 'zlaman', 'opatrz'],
        ],
        [
            'slug' => 'holowanie-pojazdu',
            'title' => 'Holowanie pojazdu',
            'prompt_any' => ['holowan', 'pojazd holuj', 'holowac'],
            'existing_article_slug' => 'holowanie-pojazdu',
        ],
        [
            'slug' => 'przyczepa-masa-wymiary-i-oswietlenie',
            'title' => 'Przyczepa: masa, wymiary i oświetlenie',
            'topic_keys' => ['driving_with_trailer', 'vehicle_load_and_passenger_safety'],
            'prompt_any' => ['przyczep'],
            'prompt_none' => ['przyczepnosc'],
            'existing_article_slug' => 'przyczepa-masa-wymiary-i-oswietlenie',
        ],
    ],
];
