<?php

return [
    'organization' => [
        'name' => env('CONTENT_ORGANIZATION_NAME', 'PrawkoNaRaz'),
        'legal_name' => env('CONTENT_ORGANIZATION_LEGAL_NAME'),
        'description' => env(
            'CONTENT_ORGANIZATION_DESCRIPTION',
            'Nowoczesna platforma edukacyjna dla kierowców, łącząca oficjalną bazę pytań WORD z algorytmami powtórek i mechanizmami gamifikacji.',
        ),
        'email' => env('CONTENT_CONTACT_EMAIL', 'kontakt@prawkonaraz.pl'),
        'logo_url' => env('CONTENT_ORGANIZATION_LOGO_URL', rtrim((string) env('APP_URL', 'http://localhost'), '/').'/favicon.png'),
        'same_as' => array_values(array_filter([
            env('CONTENT_ORGANIZATION_LINKEDIN_URL'),
            env('CONTENT_ORGANIZATION_FACEBOOK_URL'),
        ])),
    ],
    'legal_documents' => [
        'operator_address' => env('CONTENT_ORGANIZATION_ADDRESS'),
        'operator_tax_id' => env('CONTENT_ORGANIZATION_TAX_ID'),
        'privacy_email' => env('CONTENT_PRIVACY_EMAIL', env('CONTENT_CONTACT_EMAIL', 'kontakt@prawkonaraz.pl')),
        'effective_date' => env('LEGAL_DOCUMENTS_EFFECTIVE_DATE', '2026-09-04'),
        'terms_version' => env('LEGAL_TERMS_VERSION', '2026-09-04'),
        'privacy_version' => env('LEGAL_PRIVACY_VERSION', '2026-09-04'),
    ],
    'legal_content' => [
        'article_images' => [
            'zatrzymanie-i-postoj' => [
                'path' => 'images/legal/articles/zatrzymanie-i-postoj.webp',
                'alt' => 'Samochód prawidłowo zaparkowany równolegle przy krawężniku na miejskiej ulicy',
                'width' => 1400,
                'height' => 788,
            ],
            'tramwaje-i-przystanki' => [
                'path' => 'images/legal/articles/tramwaje-i-przystanki.webp',
                'alt' => 'Samochód zatrzymany przy tramwaju, z którego pasażerowie wysiadają na przystanku',
                'width' => 1400,
                'height' => 788,
            ],
            'piesi-i-przejscia' => [
                'path' => 'images/legal/articles/piesi-i-przejscia.webp',
                'alt' => 'Kierowca zatrzymany przed przejściem dla pieszych, przez które przechodzi pieszy',
                'width' => 1400,
                'height' => 788,
            ],
            'pierwszenstwo-przejazdu' => [
                'path' => 'images/legal/articles/pierwszenstwo-przejazdu.webp',
                'alt' => 'Dwa samochody ostrożnie zbliżające się do skrzyżowania z oznakowanym pierwszeństwem',
                'width' => 1400,
                'height' => 788,
            ],
            'sygnalizacja-i-osoby-kierujace-ruchem' => [
                'path' => 'images/legal/articles/sygnalizacja-i-osoby-kierujace-ruchem.webp',
                'alt' => 'Policjant kierujący ruchem na miejskim skrzyżowaniu z sygnalizacją świetlną',
                'width' => 1400,
                'height' => 788,
            ],
            'predkosc-odstep-i-hamowanie' => [
                'path' => 'images/legal/articles/predkosc-odstep-i-hamowanie.webp',
                'alt' => 'Samochody zachowujące bezpieczny odstęp na mokrej drodze szybkiego ruchu',
                'width' => 1400,
                'height' => 788,
            ],
            'zmiana-kierunku-i-pasa-ruchu' => [
                'path' => 'images/legal/articles/zmiana-kierunku-i-pasa-ruchu.webp',
                'alt' => 'Samochód zmieniający pas ruchu z włączonym kierunkowskazem na miejskiej arterii',
                'width' => 1400,
                'height' => 788,
            ],
            'wlaczanie-sie-do-ruchu' => [
                'path' => 'images/legal/articles/wlaczanie-sie-do-ruchu.webp',
                'alt' => 'Samochód wyjeżdżający z posesji przez chodnik i ustępujący uczestnikom ruchu',
                'width' => 1400,
                'height' => 788,
            ],
            'wymijanie-omijanie-cofanie' => [
                'path' => 'images/legal/articles/wymijanie-omijanie-cofanie.webp',
                'alt' => 'Samochód ostrożnie omijający pojazd cofający z miejsca parkingowego',
                'width' => 1400,
                'height' => 788,
            ],
            'wyprzedzanie' => [
                'path' => 'images/legal/articles/wyprzedzanie.webp',
                'alt' => 'Samochód bezpiecznie wyprzedzający drugi pojazd na prostej drodze poza miastem',
                'width' => 1400,
                'height' => 788,
            ],
            'autobus-wyjezdzajacy-z-przystanku' => [
                'path' => 'images/legal/articles/autobus-wyjezdzajacy-z-przystanku.webp',
                'alt' => 'Autobus wyjeżdżający z zatoki przystankowej na jezdnię w obszarze zabudowanym',
                'width' => 1400,
                'height' => 788,
            ],
            'zawracanie' => [
                'path' => 'images/legal/articles/zawracanie.webp',
                'alt' => 'Samochód wykonujący zawracanie z lewego pasa na szerokim skrzyżowaniu miejskim',
                'width' => 1400,
                'height' => 788,
            ],
            'sygnal-dzwiekowy' => [
                'path' => 'images/legal/articles/sygnal-dzwiekowy.webp',
                'alt' => 'Kierowca ostrzegający sygnałem dźwiękowym pieszego wchodzącego na jezdnię',
                'width' => 1400,
                'height' => 788,
            ],
            'zabezpieczenie-ladunku-i-wymiary' => [
                'path' => 'images/legal/articles/zabezpieczenie-ladunku-i-wymiary.webp',
                'alt' => 'Ładunek na paletach prawidłowo zabezpieczony pasami w samochodzie ciężarowym',
                'width' => 1400,
                'height' => 788,
            ],
            'przyczepa-masa-wymiary-i-oswietlenie' => [
                'path' => 'images/legal/articles/przyczepa-masa-wymiary-i-oswietlenie.webp',
                'alt' => 'Samochód osobowy ciągnący przyczepę kempingową na drodze',
                'width' => 1400,
                'height' => 788,
            ],
            'wjazd-na-przejazd-kolejowy' => [
                'path' => 'images/legal/articles/wjazd-na-przejazd-kolejowy.webp',
                'alt' => 'Samochód zatrzymany przed opuszczonymi półzaporami na przejeździe kolejowym',
                'width' => 1400,
                'height' => 788,
            ],
            'holowanie-pojazdu' => [
                'path' => 'images/legal/articles/holowanie-pojazdu.webp',
                'alt' => 'Samochód osobowy holujący drugi pojazd za pomocą oznaczonego połączenia giętkiego',
                'width' => 1400,
                'height' => 788,
            ],
            'pasy-bezpieczenstwa' => [
                'path' => 'images/legal/articles/pasy-bezpieczenstwa.webp',
                'alt' => 'Kierowca i pasażer na tylnym siedzeniu prawidłowo korzystający z pasów bezpieczeństwa',
                'width' => 1400,
                'height' => 788,
            ],
            'swiatla-do-jazdy-dziennej-i-mijania' => [
                'path' => 'images/legal/articles/swiatla-do-jazdy-dziennej-i-mijania.webp',
                'alt' => 'Samochód jadący w dzień z włączonymi światłami do jazdy dziennej',
                'width' => 1400,
                'height' => 788,
            ],
            'rogatki-i-sygnaly-na-przejezdzie-kolejowym' => [
                'path' => 'images/legal/articles/rogatki-i-sygnaly-na-przejezdzie-kolejowym.webp',
                'alt' => 'Samochód oczekujący przed częściowo podniesionymi rogatkami i działającym czerwonym sygnałem',
                'width' => 1400,
                'height' => 788,
            ],
            'swiatla-przeciwmglowe' => [
                'path' => 'images/legal/articles/swiatla-przeciwmglowe.webp',
                'alt' => 'Samochód z włączonymi przednimi światłami przeciwmgłowymi na drodze we mgle',
                'width' => 1400,
                'height' => 788,
            ],
            'foteliki-i-przewoz-dzieci' => [
                'path' => 'images/legal/articles/foteliki-i-przewoz-dzieci.webp',
                'alt' => 'Rodzic prawidłowo zapinający dziecko w foteliku na tylnym siedzeniu samochodu',
                'width' => 1400,
                'height' => 788,
            ],
            'obowiazki-uczestnika-wypadku' => [
                'path' => 'images/legal/articles/obowiazki-uczestnika-wypadku.webp',
                'alt' => 'Uczestnicy zabezpieczający miejsce wypadku i wzywający pomoc dla poszkodowanego',
                'width' => 1400,
                'height' => 788,
            ],
            'telefon-podczas-kierowania' => [
                'path' => 'images/legal/articles/telefon-podczas-kierowania.webp',
                'alt' => 'Kierowca prowadzący samochód obiema rękami z telefonem umieszczonym w uchwycie',
                'width' => 1400,
                'height' => 788,
            ],
            'swiatla-drogowe-i-oslepianie' => [
                'path' => 'images/legal/articles/swiatla-drogowe-i-oslepianie.webp',
                'alt' => 'Dwa samochody mijające się nocą bez oślepiania światłami',
                'width' => 1400,
                'height' => 788,
            ],
            'gasnica-trojkat-i-obowiazkowe-wyposazenie' => [
                'path' => 'images/legal/articles/gasnica-trojkat-i-obowiazkowe-wyposazenie.webp',
                'alt' => 'Prawidłowo zamocowana gaśnica i trójkąt ostrzegawczy w bagażniku samochodu',
                'width' => 1400,
                'height' => 788,
            ],
            'opony-bieznik-i-cisnienie' => [
                'path' => 'images/legal/articles/opony-bieznik-i-cisnienie.webp',
                'alt' => 'Pomiar głębokości bieżnika i ciśnienia w oponie samochodu',
                'width' => 1400,
                'height' => 788,
            ],
            'dokumenty-podczas-kontroli-drogowej' => [
                'path' => 'images/legal/articles/dokumenty-podczas-kontroli-drogowej.webp',
                'alt' => 'Policjant kontrolujący dokumenty kierowcy przy samochodzie podczas kontroli drogowej',
                'width' => 1400,
                'height' => 788,
            ],
            'kategorie-prawa-jazdy-i-uprawnienia' => [
                'path' => 'images/legal/articles/kategorie-prawa-jazdy-i-uprawnienia.webp',
                'alt' => 'Samochód, motocykl, czterokołowiec i ciągnik ilustrujące kategorie prawa jazdy',
                'width' => 1400,
                'height' => 788,
            ],
            'alkohol-i-srodki-dzialajace-podobnie' => [
                'path' => 'images/legal/articles/alkohol-i-srodki-dzialajace-podobnie.webp',
                'alt' => 'Kontrola trzeźwości kierowcy wykonywana przez policjanta przy zatrzymanym samochodzie',
                'width' => 1400,
                'height' => 788,
            ],
            'zielona-strzalka-warunkowa' => [
                'path' => 'images/legal/articles/zielona-strzalka-warunkowa.webp',
                'alt' => 'Samochód zatrzymany przed skrzyżowaniem przy czerwonym świetle i zielonej strzałce w prawo',
                'width' => 1400,
                'height' => 788,
            ],
            'pojazd-uprzywilejowany' => [
                'path' => 'images/legal/articles/pojazd-uprzywilejowany.webp',
                'alt' => 'Korytarz życia utworzony na wielopasowej drodze dla nadjeżdżającego ambulansu',
                'width' => 1400,
                'height' => 788,
            ],
            'sygnal-zolty-i-zolty-migajacy' => [
                'path' => 'images/legal/articles/sygnal-zolty-i-zolty-migajacy.webp',
                'alt' => 'Samochód ostrożnie zbliżający się do skrzyżowania z migającym żółtym sygnałem',
                'width' => 1400,
                'height' => 788,
            ],
        ],
    ],
    'redirects' => [
        'signs' => [
            'redirects' => [
                'b-11-zakaz-wjazdu-wozkow-rowerowych' => 'b-11-zakaz-wjazdu-wozow-recznych',
                'b-12-zakaz-wjazdu-wozkow-recznych' => 'b-12-zakaz-wjazdu-wozow-recznych-z-towarem',
                'b-32-stoj-kontrola-celna' => 'b-32-zatrzymanie-i-odprawa-celna',
                'd-4c-uliczka-bez-wyjscia-z-przejsciem' => 'd-4c-wjazd-na-droge-bez-przejazdu-z-lewej-strony',
                'd-5-pierwszenstwo-przejazdu-na-skrzyzowaniu' => 'd-5-pierwszenstwo-na-zwezonym-odcinku-jezdni',
                'd-11-poczatek-obszaru-zabudowanego' => 'd-11-poczatek-pasa-ruchu-dla-autobusow',
                'd-12-koniec-obszaru-zabudowanego' => 'd-12-pas-ruchu-dla-autobusow',
                'd-13a-parking-zadaszony' => 'd-13a-poczatek-pasa-ruchu',
                'd-14-koniec-parkowania' => 'd-14-koniec-pasa-ruchu',
                'd-18a-przejscie-podziemne-dla-pieszych' => 'd-18a-parking-miejsce-zastrzezone',
                'd-18b-przejscie-nadziemne-dla-pieszych' => 'd-18b-parking-zadaszony',
                'd-19-przejazd-rowerowy' => 'd-19-postoj-taksowek',
                'd-20-szpital' => 'd-20-koniec-postoju-taksowek',
                'd-21-stacja-opatrunkowa' => 'd-21-szpital',
                'd-21a-defibrylator-aed' => 'd-21a-policja',
                'd-22-stacja-benzynowa' => 'd-22-punkt-opatrunkowy',
                'd-23a-stacja-ladowania-pojazdow-elektrycznych' => 'd-23a-stacja-paliwowa-z-gazem-do-napedu-pojazdow',
                'd-23b-stacja-gazu-lpg' => 'd-23b-stacja-paliwowa-z-punktem-ladowania-pojazdow-elektrycznych',
                'd-23c-stacja-wodoru' => 'd-23c-punkt-ladowania-pojazdow-elektrycznych',
                'd-24-punkt-informacji-turystycznej' => 'd-24-telefon',
                'd-25-bufet-lub-kawiarnia' => 'd-25-poczta',
                'd-26-hotel-lub-motel' => 'd-26-stacja-obslugi-technicznej',
                'd-26a-pole-namiotowe' => 'd-26a-wulkanizacja',
                'd-26b-pole-kempingowe' => 'd-26b-myjnia',
                'd-26c-schronisko-mlodziezowe' => 'd-26c-toaleta-publiczna',
                'd-26d-gospoda' => 'd-26d-natrysk',
                'd-27-stacja-obslugi-pojazdow' => 'd-27-bufet-lub-kawiarnia',
                'd-29-natrysk' => 'd-29-hotel-lub-motel',
                'd-30-basen-kapaliskowy' => 'd-30-obozowisko-kemping',
                'd-31-teren-rekreacyjny' => 'd-31-obozowisko-kemping-z-podlaczeniami-elektrycznymi-do-przyczep',
                'd-32-pole-do-gry' => 'd-32-pole-biwakowe',
                'd-33-restauracja' => 'd-33-schronisko-mlodziezowe',
                'd-34a-koniec-drogi-dla-pieszych' => 'd-34a-informacja-radiowa-o-ruchu-drogowym',
                'd-34b-droga-dla-pieszych-i-rowerow' => 'd-34b-zbiorcza-tablica-informacyjna',
                'd-35-droga-dla-rowerow' => 'd-35-przejscie-podziemne-dla-pieszych',
                'd-35a-koniec-drogi-dla-rowerow' => 'd-35a-schody-ruchome-w-dol',
                'd-36-strefa-zamieszkania' => 'd-36-przejscie-nadziemne-dla-pieszych',
                'd-36a-koniec-strefy-zamieszkania' => 'd-36a-schody-ruchome-w-gore',
                'd-37-strefa-ruchu' => 'd-37-tunel',
                'd-38-koniec-strefy-ruchu' => 'd-38-koniec-tunelu',
                'd-40-strefa-ograniczonej-predkosci' => 'd-40-strefa-zamieszkania',
                'd-41-koniec-strefy-ograniczonej-predkosci' => 'd-41-koniec-strefy-zamieszkania',
                'd-42-strefa-parkowania' => 'd-42-obszar-zabudowany',
                'd-43-koniec-strefy-parkowania' => 'd-43-koniec-obszaru-zabudowanego',
                'd-44-strefa-czystego-transportu' => 'd-44-strefa-platnego-parkowania',
                'd-45-policja' => 'd-45-koniec-strefy-platnego-parkowania',
                'd-46-punkt-kontrolny-pojazdow' => 'd-46-droga-wewnetrzna',
                'd-47-punkt-kontroli-celnej' => 'd-47-koniec-drogi-wewnetrznej',
                'd-48-granica-panstwa' => 'd-48-zmiana-pierwszenstwa-na-skrzyzowaniu-rownorzednym',
                'd-48a-wjazd-lub-przejazd-zabroniony' => 'd-48a-zmiana-pierwszenstwa',
                'd-49-punkt-poboru-oplat' => 'd-49-pobor-oplat',
                'd-50-tablica-informacyjna-na-obszarze-zabudowanym' => 'd-50-zatoka',
                'd-51-pas-ruchu-dla-autobusow' => 'd-51-automatyczna-kontrola-predkosci',
                'd-51b-pas-ruchu-dla-rowerow' => 'd-51b-koniec-automatycznej-kontroli-sredniej-predkosci',
                'd-52-miejsce-szczegolnie-niebezpieczne' => 'd-52-strefa-ruchu',
                'd-53-droga-dla-pieszych-i-rowerow-razem' => 'd-53-koniec-strefy-ruchu',
                'd-54-obowiazek-platnosci-za-postoj' => 'd-54-strefa-czystego-transportu',
                'd-55-koniec-obowiazku-platnosci-za-postoj' => 'd-55-koniec-strefy-czystego-transportu',
            ],
            'gone' => [
                'd-13-parking',
                'd-13b-parking-dla-pojazdow-osob-niepelnosprawnych',
                'd-51aa-pas-ruchu-dla-autobusow-i-rowerow',
                's-2a-sygnal-dopuszczajacy-skret-w-prawo',
                's-2b-sygnal-dopuszczajacy-skret-w-lewo',
                's-3-sygnalizator-kierunkowy',
            ],
        ],
        'categories' => [
            'redirects' => [],
            'gone' => [],
        ],
        'authors' => [
            'redirects' => [
                'redakcja-brd' => 'katarzyna-wisniewska',
            ],
            'gone' => [],
        ],
    ],
];
