<?php

namespace App\Http\Controllers;

use Illuminate\Http\Response;

class RobotsController extends Controller
{
    public function __invoke(): Response
    {
        $lines = [
            '# AI search and user-requested fetchers: public content is allowed.',
            'User-agent: OAI-SearchBot',
            'User-agent: ChatGPT-User',
            'User-agent: Claude-SearchBot',
            'User-agent: Claude-User',
            'User-agent: PerplexityBot',
            'User-agent: Perplexity-User',
            'User-agent: Applebot',
            'User-agent: DuckAssistBot',
            'User-agent: MistralAI-User',
            'User-agent: Meta-ExternalFetcher',
            'User-agent: ManusBot',
            'User-agent: Manus Bot',
            'User-agent: TerracottaBot',
            'User-agent: Terracotta Bot',
            'Allow: /',
            'Disallow: /admin/',
            'Disallow: /api/',
            'Disallow: /dashboard',
            'Disallow: /auth/',
            'Disallow: /checkout/',
            'Disallow: /konto/',
            'Disallow: /profile/',
            'Disallow: /nauka/',
            'Disallow: /zaproszenie/',
            'Disallow: /login',
            'Disallow: /register',
            'Disallow: /forgot-password',
            'Disallow: /reset-password/',
            'Disallow: /verify-email/',
            'Disallow: /email/',
            'Disallow: /confirm-password',
            'Disallow: /password',
            '',
            '# AI training crawlers: search visibility is welcome, model training is not granted.',
            'User-agent: GPTBot',
            'User-agent: ClaudeBot',
            'User-agent: Google-Extended',
            'User-agent: CCBot',
            'User-agent: Bytespider',
            'User-agent: Applebot-Extended',
            'User-agent: meta-externalagent',
            'User-agent: Meta-ExternalAgent',
            'User-agent: Amazonbot',
            'User-agent: FacebookBot',
            'User-agent: Google-CloudVertexBot',
            'User-agent: PetalBot',
            'User-agent: TikTokSpider',
            'User-agent: TikTok Spider',
            'User-agent: Timpibot',
            'User-agent: ProRataInc',
            'User-agent: NovellumAICrawl',
            'User-agent: Novellum AI Crawl',
            'User-agent: AnchorBrowser',
            'User-agent: Anchor Browser',
            'Disallow: /',
            '',
            'User-agent: *',
            'Content-Signal: search=yes,ai-input=yes,ai-train=no',
            'Allow: /',
            'Disallow: /admin/',
            'Disallow: /api/',
            'Disallow: /dashboard',
            'Disallow: /auth/',
            'Disallow: /checkout/',
            'Disallow: /konto/',
            'Disallow: /profile/',
            'Disallow: /nauka/',
            'Disallow: /zaproszenie/',
            'Disallow: /login',
            'Disallow: /register',
            'Disallow: /forgot-password',
            'Disallow: /reset-password/',
            'Disallow: /verify-email/',
            'Disallow: /email/',
            'Disallow: /confirm-password',
            'Disallow: /password',
            '',
            'Sitemap: '.route('sitemap.index'),
        ];

        return response(implode("\n", $lines)."\n", 200, [
            'Content-Type' => 'text/plain; charset=UTF-8',
        ]);
    }
}
