<?php

namespace App\Support;

class PolishInformationalSignCatalog
{
    /**
     * @return list<array{code: string, slug: string, name: string, primary_query: string}>
     */
    public function all(): array
    {
        return [
            ['code' => 'D-1', 'slug' => 'd-1-droga-z-pierwszenstwem', 'name' => 'Droga z pierwszeństwem', 'primary_query' => 'd-1 droga z pierwszeństwem'],
            ['code' => 'D-2', 'slug' => 'd-2-koniec-drogi-z-pierwszenstwem', 'name' => 'Koniec drogi z pierwszeństwem', 'primary_query' => 'd-2 koniec drogi z pierwszeństwem'],
            ['code' => 'D-3', 'slug' => 'd-3-droga-jednokierunkowa', 'name' => 'Droga jednokierunkowa', 'primary_query' => 'd-3 droga jednokierunkowa'],
            ['code' => 'D-4a', 'slug' => 'd-4a-droga-bez-przejazdu', 'name' => 'Droga bez przejazdu', 'primary_query' => 'd-4a droga bez przejazdu'],
            ['code' => 'D-4b', 'slug' => 'd-4b-wjazd-na-droge-bez-przejazdu', 'name' => 'Wjazd na drogę bez przejazdu', 'primary_query' => 'd-4b wjazd na drogę bez przejazdu'],
            ['code' => 'D-4c', 'slug' => 'd-4c-wjazd-na-droge-bez-przejazdu-z-lewej-strony', 'name' => 'Wjazd na drogę bez przejazdu z lewej strony', 'primary_query' => 'd-4c wjazd na drogę bez przejazdu z lewej strony'],
            ['code' => 'D-5', 'slug' => 'd-5-pierwszenstwo-na-zwezonym-odcinku-jezdni', 'name' => 'Pierwszeństwo na zwężonym odcinku jezdni', 'primary_query' => 'd-5 pierwszeństwo na zwężonym odcinku jezdni'],
            ['code' => 'D-6', 'slug' => 'd-6-przejscie-dla-pieszych', 'name' => 'Przejście dla pieszych', 'primary_query' => 'd-6 przejście dla pieszych'],
            ['code' => 'D-6a', 'slug' => 'd-6a-przejazd-dla-rowerzystow', 'name' => 'Przejazd dla rowerzystów', 'primary_query' => 'd-6a przejazd dla rowerzystów'],
            ['code' => 'D-6b', 'slug' => 'd-6b-przejscie-dla-pieszych-i-przejazd-dla-rowerow', 'name' => 'Przejście dla pieszych i przejazd dla rowerów', 'primary_query' => 'd-6b przejście dla pieszych i przejazd dla rowerów'],
            ['code' => 'D-7', 'slug' => 'd-7-droga-ekspresowa', 'name' => 'Droga ekspresowa', 'primary_query' => 'd-7 droga ekspresowa'],
            ['code' => 'D-8', 'slug' => 'd-8-koniec-drogi-ekspresowej', 'name' => 'Koniec drogi ekspresowej', 'primary_query' => 'd-8 koniec drogi ekspresowej'],
            ['code' => 'D-9', 'slug' => 'd-9-autostrada', 'name' => 'Autostrada', 'primary_query' => 'd-9 autostrada'],
            ['code' => 'D-10', 'slug' => 'd-10-koniec-autostrady', 'name' => 'Koniec autostrady', 'primary_query' => 'd-10 koniec autostrady'],
            ['code' => 'D-11', 'slug' => 'd-11-poczatek-pasa-ruchu-dla-autobusow', 'name' => 'Początek pasa ruchu dla autobusów', 'primary_query' => 'd-11 początek pasa ruchu dla autobusów'],
            ['code' => 'D-12', 'slug' => 'd-12-pas-ruchu-dla-autobusow', 'name' => 'Pas ruchu dla autobusów', 'primary_query' => 'd-12 pas ruchu dla autobusów'],
            ['code' => 'D-13a', 'slug' => 'd-13a-poczatek-pasa-ruchu', 'name' => 'Początek pasa ruchu', 'primary_query' => 'd-13a początek pasa ruchu'],
            ['code' => 'D-14', 'slug' => 'd-14-koniec-pasa-ruchu', 'name' => 'Koniec pasa ruchu', 'primary_query' => 'd-14 koniec pasa ruchu'],
            ['code' => 'D-15', 'slug' => 'd-15-przystanek-autobusowy', 'name' => 'Przystanek autobusowy', 'primary_query' => 'd-15 przystanek autobusowy'],
            ['code' => 'D-17', 'slug' => 'd-17-przystanek-tramwajowy', 'name' => 'Przystanek tramwajowy', 'primary_query' => 'd-17 przystanek tramwajowy'],
            ['code' => 'D-18', 'slug' => 'd-18-parking', 'name' => 'Parking', 'primary_query' => 'd-18 parking'],
            ['code' => 'D-18a', 'slug' => 'd-18a-parking-miejsce-zastrzezone', 'name' => 'Parking - miejsce zastrzeżone', 'primary_query' => 'd-18a parking miejsce zastrzeżone'],
            ['code' => 'D-18b', 'slug' => 'd-18b-parking-zadaszony', 'name' => 'Parking zadaszony', 'primary_query' => 'd-18b parking zadaszony'],
            ['code' => 'D-19', 'slug' => 'd-19-postoj-taksowek', 'name' => 'Postój taksówek', 'primary_query' => 'd-19 postój taksówek'],
            ['code' => 'D-20', 'slug' => 'd-20-koniec-postoju-taksowek', 'name' => 'Koniec postoju taksówek', 'primary_query' => 'd-20 koniec postoju taksówek'],
            ['code' => 'D-21', 'slug' => 'd-21-szpital', 'name' => 'Szpital', 'primary_query' => 'd-21 szpital'],
            ['code' => 'D-21a', 'slug' => 'd-21a-policja', 'name' => 'Policja', 'primary_query' => 'd-21a policja'],
            ['code' => 'D-22', 'slug' => 'd-22-punkt-opatrunkowy', 'name' => 'Punkt opatrunkowy', 'primary_query' => 'd-22 punkt opatrunkowy'],
            ['code' => 'D-23', 'slug' => 'd-23-stacja-paliwowa', 'name' => 'Stacja paliwowa', 'primary_query' => 'd-23 stacja paliwowa'],
            ['code' => 'D-23a', 'slug' => 'd-23a-stacja-paliwowa-z-gazem-do-napedu-pojazdow', 'name' => 'Stacja paliwowa z gazem do napędu pojazdów', 'primary_query' => 'd-23a stacja paliwowa z gazem do napędu pojazdów'],
            ['code' => 'D-23b', 'slug' => 'd-23b-stacja-paliwowa-z-punktem-ladowania-pojazdow-elektrycznych', 'name' => 'Stacja paliwowa z punktem ładowania pojazdów elektrycznych', 'primary_query' => 'd-23b stacja paliwowa z punktem ładowania pojazdów elektrycznych'],
            ['code' => 'D-23c', 'slug' => 'd-23c-punkt-ladowania-pojazdow-elektrycznych', 'name' => 'Punkt ładowania pojazdów elektrycznych', 'primary_query' => 'd-23c punkt ładowania pojazdów elektrycznych'],
            ['code' => 'D-24', 'slug' => 'd-24-telefon', 'name' => 'Telefon', 'primary_query' => 'd-24 telefon'],
            ['code' => 'D-25', 'slug' => 'd-25-poczta', 'name' => 'Poczta', 'primary_query' => 'd-25 poczta'],
            ['code' => 'D-26', 'slug' => 'd-26-stacja-obslugi-technicznej', 'name' => 'Stacja obsługi technicznej', 'primary_query' => 'd-26 stacja obsługi technicznej'],
            ['code' => 'D-26a', 'slug' => 'd-26a-wulkanizacja', 'name' => 'Wulkanizacja', 'primary_query' => 'd-26a wulkanizacja'],
            ['code' => 'D-26b', 'slug' => 'd-26b-myjnia', 'name' => 'Myjnia', 'primary_query' => 'd-26b myjnia'],
            ['code' => 'D-26c', 'slug' => 'd-26c-toaleta-publiczna', 'name' => 'Toaleta publiczna', 'primary_query' => 'd-26c toaleta publiczna'],
            ['code' => 'D-26d', 'slug' => 'd-26d-natrysk', 'name' => 'Natrysk', 'primary_query' => 'd-26d natrysk'],
            ['code' => 'D-27', 'slug' => 'd-27-bufet-lub-kawiarnia', 'name' => 'Bufet lub kawiarnia', 'primary_query' => 'd-27 bufet lub kawiarnia'],
            ['code' => 'D-28', 'slug' => 'd-28-restauracja', 'name' => 'Restauracja', 'primary_query' => 'd-28 restauracja'],
            ['code' => 'D-29', 'slug' => 'd-29-hotel-lub-motel', 'name' => 'Hotel lub motel', 'primary_query' => 'd-29 hotel lub motel'],
            ['code' => 'D-30', 'slug' => 'd-30-obozowisko-kemping', 'name' => 'Obozowisko (kemping)', 'primary_query' => 'd-30 obozowisko kemping'],
            ['code' => 'D-31', 'slug' => 'd-31-obozowisko-kemping-z-podlaczeniami-elektrycznymi-do-przyczep', 'name' => 'Obozowisko (kemping) z podłączeniami elektrycznymi do przyczep', 'primary_query' => 'd-31 obozowisko kemping z podłączeniami elektrycznymi do przyczep'],
            ['code' => 'D-32', 'slug' => 'd-32-pole-biwakowe', 'name' => 'Pole biwakowe', 'primary_query' => 'd-32 pole biwakowe'],
            ['code' => 'D-33', 'slug' => 'd-33-schronisko-mlodziezowe', 'name' => 'Schronisko młodzieżowe', 'primary_query' => 'd-33 schronisko młodzieżowe'],
            ['code' => 'D-34', 'slug' => 'd-34-punkt-informacji-turystycznej', 'name' => 'Punkt informacji turystycznej', 'primary_query' => 'd-34 punkt informacji turystycznej'],
            ['code' => 'D-34a', 'slug' => 'd-34a-informacja-radiowa-o-ruchu-drogowym', 'name' => 'Informacja radiowa o ruchu drogowym', 'primary_query' => 'd-34a informacja radiowa o ruchu drogowym'],
            ['code' => 'D-34b', 'slug' => 'd-34b-zbiorcza-tablica-informacyjna', 'name' => 'Zbiorcza tablica informacyjna', 'primary_query' => 'd-34b zbiorcza tablica informacyjna'],
            ['code' => 'D-35', 'slug' => 'd-35-przejscie-podziemne-dla-pieszych', 'name' => 'Przejście podziemne dla pieszych', 'primary_query' => 'd-35 przejście podziemne dla pieszych'],
            ['code' => 'D-35a', 'slug' => 'd-35a-schody-ruchome-w-dol', 'name' => 'Schody ruchome w dół', 'primary_query' => 'd-35a schody ruchome w dół'],
            ['code' => 'D-36', 'slug' => 'd-36-przejscie-nadziemne-dla-pieszych', 'name' => 'Przejście nadziemne dla pieszych', 'primary_query' => 'd-36 przejście nadziemne dla pieszych'],
            ['code' => 'D-36a', 'slug' => 'd-36a-schody-ruchome-w-gore', 'name' => 'Schody ruchome w górę', 'primary_query' => 'd-36a schody ruchome w górę'],
            ['code' => 'D-37', 'slug' => 'd-37-tunel', 'name' => 'Tunel', 'primary_query' => 'd-37 tunel'],
            ['code' => 'D-38', 'slug' => 'd-38-koniec-tunelu', 'name' => 'Koniec tunelu', 'primary_query' => 'd-38 koniec tunelu'],
            ['code' => 'D-40', 'slug' => 'd-40-strefa-zamieszkania', 'name' => 'Strefa zamieszkania', 'primary_query' => 'd-40 strefa zamieszkania'],
            ['code' => 'D-41', 'slug' => 'd-41-koniec-strefy-zamieszkania', 'name' => 'Koniec strefy zamieszkania', 'primary_query' => 'd-41 koniec strefy zamieszkania'],
            ['code' => 'D-42', 'slug' => 'd-42-obszar-zabudowany', 'name' => 'Obszar zabudowany', 'primary_query' => 'd-42 obszar zabudowany'],
            ['code' => 'D-43', 'slug' => 'd-43-koniec-obszaru-zabudowanego', 'name' => 'Koniec obszaru zabudowanego', 'primary_query' => 'd-43 koniec obszaru zabudowanego'],
            ['code' => 'D-44', 'slug' => 'd-44-strefa-platnego-parkowania', 'name' => 'Strefa płatnego parkowania', 'primary_query' => 'd-44 strefa płatnego parkowania'],
            ['code' => 'D-45', 'slug' => 'd-45-koniec-strefy-platnego-parkowania', 'name' => 'Koniec strefy płatnego parkowania', 'primary_query' => 'd-45 koniec strefy płatnego parkowania'],
            ['code' => 'D-46', 'slug' => 'd-46-droga-wewnetrzna', 'name' => 'Droga wewnętrzna', 'primary_query' => 'd-46 droga wewnętrzna'],
            ['code' => 'D-47', 'slug' => 'd-47-koniec-drogi-wewnetrznej', 'name' => 'Koniec drogi wewnętrznej', 'primary_query' => 'd-47 koniec drogi wewnętrznej'],
            ['code' => 'D-48', 'slug' => 'd-48-zmiana-pierwszenstwa-na-skrzyzowaniu-rownorzednym', 'name' => 'Zmiana pierwszeństwa na skrzyżowaniu równorzędnym', 'primary_query' => 'd-48 zmiana pierwszeństwa na skrzyżowaniu równorzędnym'],
            ['code' => 'D-48a', 'slug' => 'd-48a-zmiana-pierwszenstwa', 'name' => 'Zmiana pierwszeństwa', 'primary_query' => 'd-48a zmiana pierwszeństwa'],
            ['code' => 'D-49', 'slug' => 'd-49-pobor-oplat', 'name' => 'Pobór opłat', 'primary_query' => 'd-49 pobór opłat'],
            ['code' => 'D-50', 'slug' => 'd-50-zatoka', 'name' => 'Zatoka', 'primary_query' => 'd-50 zatoka'],
            ['code' => 'D-51', 'slug' => 'd-51-automatyczna-kontrola-predkosci', 'name' => 'Automatyczna kontrola prędkości', 'primary_query' => 'd-51 automatyczna kontrola prędkości'],
            ['code' => 'D-51a', 'slug' => 'd-51a-automatyczna-kontrola-sredniej-predkosci', 'name' => 'Automatyczna kontrola średniej prędkości', 'primary_query' => 'd-51a automatyczna kontrola średniej prędkości'],
            ['code' => 'D-51b', 'slug' => 'd-51b-koniec-automatycznej-kontroli-sredniej-predkosci', 'name' => 'Koniec automatycznej kontroli średniej prędkości', 'primary_query' => 'd-51b koniec automatycznej kontroli średniej prędkości'],
            ['code' => 'D-52', 'slug' => 'd-52-strefa-ruchu', 'name' => 'Strefa ruchu', 'primary_query' => 'd-52 strefa ruchu'],
            ['code' => 'D-53', 'slug' => 'd-53-koniec-strefy-ruchu', 'name' => 'Koniec strefy ruchu', 'primary_query' => 'd-53 koniec strefy ruchu'],
            ['code' => 'D-54', 'slug' => 'd-54-strefa-czystego-transportu', 'name' => 'Strefa czystego transportu', 'primary_query' => 'd-54 strefa czystego transportu'],
            ['code' => 'D-55', 'slug' => 'd-55-koniec-strefy-czystego-transportu', 'name' => 'Koniec strefy czystego transportu', 'primary_query' => 'd-55 koniec strefy czystego transportu'],
        ];
    }
}
