<?php

namespace App\Support;

use Illuminate\Support\Str;

class PolishWarningSignContentBuilder
{
    /**
     * @param  array{code: string, slug: string, name: string, primary_query: string}  $sign
     * @return array<string, mixed>
     */
    public function build(array $sign, int $index): array
    {
        $config = $this->warningConfig()[$sign['code']] ?? $this->fallbackConfig($sign);
        $assetKey = $sign['slug'];
        $assetPath = "traffic-signs/signs/warnings/{$assetKey}.webp";
        $imageAlt = "{$sign['code']} {$sign['name']}";

        return [
            'intro_definition' => "Znak {$sign['code']} ostrzega przed {$config['hazard']}. To sygnał, że kierowca powinien zareagować wcześniej niż zwykle i przygotować się na zmianę warunków jazdy.",
            'meaning' => $config['meaning'],
            'placement' => $config['placement'],
            'driver_behavior' => $config['behavior'],
            'legal_summary' => "To znak ostrzegawczy, więc sam z siebie nie wprowadza zakazu tak jak znaki z grupy B. W praktyce jednak {$sign['code']} podnosi wymagany poziom ostrożności: kierowca powinien odpowiednio wcześniej dostosować prędkość, tor jazdy i zakres obserwacji do zagrożenia widocznego na znaku.",
            'fine_summary' => "Największe ryzyko przy {$sign['code']} nie polega na \"minięciu znaku\", tylko na zbyt późnej reakcji na zagrożenie, przed którym ostrzega. Jeśli kierowca nie dostosuje zachowania do warunków, łatwo dochodzi tu do błędu ocenianego przez pryzmat niedostosowania prędkości, braku ostrożności albo naruszenia pierwszeństwa.",
            'common_mistakes' => $config['mistake'],
            'editorial_notes' => $config['editorial_notes'],
            'review_notes' => 'Szkic merytoryczny przygotowany dla pełnego pokrycia kategorii znaków ostrzegawczych. Przed publikacją zrobić pass redakcyjny na przykładach sytuacyjnych i na różnicach wobec podobnych znaków z grupy A.',
            'source_notes' => 'Treść bazowa przygotowana na podstawie urzędowego wykazu znaków ostrzegawczych i praktyki szkolenia kierowców. Przed publikacją potwierdzić finalny wording, przykłady ruchowe i ewentualne powiązania z tabliczkami lub oznakowaniem towarzyszącym.',
            'faq_items' => [
                [
                    'question' => "Na co znak {$sign['code']} każe przygotować się kierowcy?",
                    'answer' => $config['faq_preparation'],
                ],
                [
                    'question' => "Jaki błąd najczęściej pojawia się przy znaku {$sign['code']}?",
                    'answer' => $config['faq_mistake'],
                ],
            ],
            'meta_title' => "{$sign['code']} {$sign['name']} - znaczenie, zagrożenie i zachowanie kierowcy",
            'meta_description' => "Sprawdź, co oznacza znak {$sign['code']} {$sign['name']}, gdzie najczęściej występuje i jak przygotować reakcję kierowcy przed miejscem zagrożenia.",
            'image_path' => $assetPath,
            'image_alt' => $imageAlt,
            'image_width' => 1200,
            'image_height' => 1200,
            'og_image_path' => $assetPath,
            'og_image_alt' => $imageAlt,
            'og_image_width' => 1200,
            'og_image_height' => 1200,
            'sort_order' => 100 + ($index * 10),
            'legal_reference_label' => 'Rozporządzenie w sprawie znaków i sygnałów drogowych',
            'legal_reference_url' => 'https://isap.sejm.gov.pl/',
        ];
    }

    /**
     * @return array<string, array{hazard: string, meaning: string, placement: string, behavior: string, mistake: string, faq_preparation: string, faq_mistake: string, editorial_notes: string}>
     */
    protected function warningConfig(): array
    {
        return [
            'A-1' => [
                'hazard' => 'niebezpiecznym zakrętem w prawo',
                'meaning' => 'Ten znak uprzedza, że tor jazdy za chwilę wyraźnie odchyla się w prawo i może wymagać wcześniejszego zdjęcia nogi z gazu, lepszego ustawienia pojazdu i kontroli przyczepności.',
                'placement' => 'Najczęściej stoi przed łukami drogi o ograniczonej widoczności, w miejscach o podwyższonym ryzyku wyniesienia pojazdu na zewnętrzną stronę zakrętu albo tam, gdzie zakręt pojawia się po szybszym odcinku.',
                'behavior' => 'Podejdź do znaku z wcześniejszym wytraceniem prędkości, obserwuj pobocze i krawędź jezdni oraz nie wchodź w zakręt z założeniem, że ocenę sytuacji zrobisz dopiero w jego środku.',
                'mistake' => 'Najczęstszy błąd to zbyt późne hamowanie i wejście w zakręt z prędkością dobraną do poprzedniego odcinka drogi, a nie do realnej geometrii łuku.',
                'faq_preparation' => 'Na wcześniejsze wytracenie prędkości i na zakręt, który może ograniczać widoczność albo przyczepność bardziej, niż wygląda z daleka.',
                'faq_mistake' => 'Najczęściej kierowca hamuje za późno i zaczyna korygować tor jazdy dopiero wtedy, gdy auto jest już w zakręcie.',
                'editorial_notes' => 'Powiązać później z A-2, A-3 i A-4 jako mini-klaster o czytaniu zakrętów.',
            ],
            'A-2' => [
                'hazard' => 'niebezpiecznym zakrętem w lewo',
                'meaning' => 'To ostrzeżenie, że droga za chwilę skręca w lewo i może wymagać szybszej reakcji niż kierowca zakłada na podstawie samego widoku odcinka dojazdowego.',
                'placement' => 'Najczęściej pojawia się przed łukami o ograniczonej widoczności, na drogach lokalnych i pozamiejskich oraz wszędzie tam, gdzie zakręt pojawia się po fragmencie zachęcającym do zbyt szybkiej jazdy.',
                'behavior' => 'Ustal prędkość przed wejściem w zakręt, patrz daleko po kierunku łuku i nie odkładaj decyzji o redukcji prędkości do chwili, gdy auto już zaczyna skręcać.',
                'mistake' => 'Częsty błąd to wchodzenie w zakręt po lewej z tempem dobranym do prostej i ratowanie sytuacji gwałtownym hamowaniem już podczas skrętu.',
                'faq_preparation' => 'Na zakręt w lewo, który może ograniczać widoczność i wymagać wcześniejszego ustawienia prędkości oraz toru jazdy.',
                'faq_mistake' => 'Najczęściej problemem jest zbyt późne rozpoznanie geometrii zakrętu i próba redukcji prędkości dopiero w trakcie manewru.',
                'editorial_notes' => 'Przy review dodać przykład różnicy między pojedynczym zakrętem a serią zakrętów.',
            ],
            'A-3' => [
                'hazard' => 'niebezpiecznymi zakrętami, z których pierwszy prowadzi w prawo',
                'meaning' => 'Znak zapowiada sekwencję zakrętów, a nie pojedynczy łuk. Kierowca powinien przygotować się na dłuższy odcinek wymagający stabilnej prędkości i płynnego prowadzenia auta.',
                'placement' => 'Najczęściej stoi przed serpentynami, ciągami łuków na drogach lokalnych i górskich oraz na odcinkach, gdzie po pierwszym zakręcie szybko następuje kolejny w przeciwną stronę.',
                'behavior' => 'Zmniejsz prędkość już przed pierwszym łukiem i nie przyspieszaj pochopnie po jego wyjściu. Ważne jest tu zarządzanie całym odcinkiem, a nie tylko pierwszym skrętem.',
                'mistake' => 'Najczęstszy błąd to potraktowanie znaku jak zwykłego ostrzeżenia o jednym zakręcie i przyspieszenie zbyt wcześnie po minięciu pierwszego łuku.',
                'faq_preparation' => 'Na serię zakrętów, w której pierwszy prowadzi w prawo, ale zagrożenie dotyczy całego odcinka o zmiennej geometrii.',
                'faq_mistake' => 'Kierowcy często skupiają się tylko na pierwszym zakręcie i nie zostawiają zapasu na kolejne zmiany kierunku.',
                'editorial_notes' => 'Dobrze spiąć z A-4 oraz z materiałem o doborze prędkości na ciąg zakrętów.',
            ],
            'A-4' => [
                'hazard' => 'niebezpiecznymi zakrętami, z których pierwszy prowadzi w lewo',
                'meaning' => 'To ostrzeżenie o odcinku zakrętów następujących po sobie. Kierowca powinien od początku prowadzić auto tak, by mieć zapas nie tylko na pierwszy, ale na cały ciąg zmian kierunku.',
                'placement' => 'Najczęściej pojawia się na krętych odcinkach dróg lokalnych i pozamiejskich, gdzie zmiany kierunku następują szybko jedna po drugiej.',
                'behavior' => 'Wcześniej wytracaj prędkość, patrz daleko przez cały układ zakrętów i unikaj gwałtownych korekt po wyjściu z pierwszego łuku.',
                'mistake' => 'Typowy błąd to ustawienie prędkości tylko pod pierwszy zakręt i brak rezerwy na kolejne łuki o odmiennej geometrii.',
                'faq_preparation' => 'Na cały sekwencyjny odcinek zakrętów, a nie tylko na pierwszy łuk w lewo widoczny na znaku.',
                'faq_mistake' => 'Najczęściej kierowca wraca do gazu zbyt wcześnie po pierwszym zakręcie i dopiero potem orientuje się, że odcinek dalej wymaga takiej samej ostrożności.',
                'editorial_notes' => 'Połączyć z A-3 w mini-klaster o serii zakrętów.',
            ],
            'A-5' => [
                'hazard' => 'skrzyżowaniem dróg, na którym kierowca powinien wcześniej uporządkować obserwację',
                'meaning' => 'Znak nie mówi jeszcze, kto ma pierwszeństwo, ale ostrzega, że zbliża się skrzyżowanie wymagające wcześniejszego przygotowania do oceny relacji ruchu.',
                'placement' => 'Najczęściej stoi przed skrzyżowaniami o słabszej widoczności lub takimi, które z daleka nie są czytelne dla kierowcy jadącego z większą prędkością.',
                'behavior' => 'Zdejmij nogę z gazu wcześniej, zacznij obserwować pobocza i wloty boczne, a nie dopiero środek jezdni przed sobą. Przy tym znaku ważne jest przygotowanie decyzji jeszcze przed dojazdem do skrzyżowania.',
                'mistake' => 'Częsty błąd to traktowanie znaku jak neutralnej informacji o przecięciu dróg i brak realnej zmiany tempa jazdy oraz szerokości obserwacji.',
                'faq_preparation' => 'Na skrzyżowanie, które wymaga wcześniejszego uporządkowania obserwacji i gotowości do ustalenia relacji pierwszeństwa.',
                'faq_mistake' => 'Najczęściej kierowca zauważa znak, ale nie zaczyna odpowiednio wcześnie skanować wlotów bocznych i dojeżdża do skrzyżowania za szybko.',
                'editorial_notes' => 'Dobry kandydat do pierwszego warning rolloutu razem z A-6 i A-8.',
            ],
            'A-6a' => [
                'hazard' => 'skrzyżowaniem z drogą podporządkowaną występującą po obu stronach',
                'meaning' => 'To ostrzeżenie, że na najbliższym skrzyżowaniu do drogi głównej dochodzą podporządkowane wloty po obu stronach. Kierowca musi wcześniej porządkować obserwację całego układu.',
                'placement' => 'Najczęściej występuje przed skrzyżowaniami, których układ nie jest z daleka czytelny albo gdzie boczne wloty łatwo przeoczyć przy jeździe ze stałą prędkością.',
                'behavior' => 'Podejdź do znaku z wcześniejszym skanowaniem obu stron drogi i nie koncentruj się wyłącznie na wlocie, który pierwszy wpada w pole widzenia.',
                'mistake' => 'Najczęstszy błąd to zauważenie tylko jednego z podporządkowanych wlotów i uproszczenie obrazu skrzyżowania jeszcze przed dojazdem.',
                'faq_preparation' => 'Na skrzyżowanie, na którym trzeba kontrolować możliwość wjazdu pojazdów z obu stron drogi podporządkowanej.',
                'faq_mistake' => 'Kierowca często obserwuje tylko jedną stronę i zbyt późno orientuje się, że układ skrzyżowania jest symetryczny.',
                'editorial_notes' => 'Utrzymać spójność z A-6b, A-6c, A-6d i A-6e.',
            ],
            'A-6b' => [
                'hazard' => 'skrzyżowaniem z drogą podporządkowaną po prawej stronie',
                'meaning' => 'Znak uprzedza o podporządkowanym wlocie po prawej. Kierowca powinien odpowiednio wcześnie przygotować obserwację tego kierunku i nie dać się zaskoczyć pojazdom dojeżdżającym z boku.',
                'placement' => 'Najczęściej stoi przed wlotami bocznymi, które łatwo przeoczyć na szybszych odcinkach lub przy ograniczonej czytelności pobocza.',
                'behavior' => 'Zacznij wcześniej kontrolować prawą stronę i ogranicz prędkość tak, by dojazd do skrzyżowania nie wymuszał nerwowej decyzji w ostatniej chwili.',
                'mistake' => 'Typowy błąd to patrzenie głównie na kierunek jazdy i zbyt późne przesunięcie uwagi na prawy wlot podporządkowany.',
                'faq_preparation' => 'Na możliwość pojawienia się pojazdów z podporządkowanego wlotu po prawej stronie.',
                'faq_mistake' => 'Najczęściej kierowca za późno zaczyna obserwować prawy wlot i dojeżdża do skrzyżowania bez gotowego planu reakcji.',
                'editorial_notes' => 'Dobrze połączyć z A-6c jako materiał o asymetrii obserwacji na skrzyżowaniach.',
            ],
            'A-6c' => [
                'hazard' => 'skrzyżowaniem z drogą podporządkowaną po lewej stronie',
                'meaning' => 'To ostrzeżenie, że w najbliższym punkcie droga podporządkowana dochodzi z lewej. Kierowca ma wcześniej przygotować obserwację tej strony i ustawić prędkość pod ocenę sytuacji na skrzyżowaniu.',
                'placement' => 'Najczęściej pojawia się tam, gdzie lewy wlot podporządkowany nie jest czytelny z większej odległości albo łatwo ginie w tle zabudowy i zieleni.',
                'behavior' => 'Zwolnij wcześniej i patrz szerzej po lewej stronie, zanim dojedziesz do samego wlotu skrzyżowania.',
                'mistake' => 'Częsty błąd to zbyt późne zauważenie lewego wlotu i skupienie uwagi głównie na prawej krawędzi jezdni lub torze jazdy przed autem.',
                'faq_preparation' => 'Na podporządkowany wlot po lewej, który może wymagać wcześniejszej obserwacji niż sugeruje to sam widok drogi.',
                'faq_mistake' => 'Najczęściej kierowca nie przesuwa uwagi na lewą stronę odpowiednio wcześnie i zostaje zaskoczony dopiero przy samym skrzyżowaniu.',
                'editorial_notes' => 'Trzymać razem z A-6b w klastrze o czytaniu wlotów podporządkowanych.',
            ],
            'A-6d' => [
                'hazard' => 'wlotem drogi jednokierunkowej z prawej strony',
                'meaning' => 'Znak ostrzega o wlocie drogi jednokierunkowej z prawej. W praktyce kierowca powinien spodziewać się ruchu, który pojawi się z konkretnego kierunku i może mieć inną dynamikę niż na zwykłym wlocie bocznym.',
                'placement' => 'Najczęściej stoi tam, gdzie układ skrzyżowania lub zabudowa utrudnia szybkie rozpoznanie, że z prawej dochodzi droga jednokierunkowa.',
                'behavior' => 'Obserwuj prawą stronę nie tylko pod kątem samego wlotu, ale też potencjalnego tempa wjazdu pojazdów poruszających się z tej relacji.',
                'mistake' => 'Najczęstszy błąd to potraktowanie znaku jak zwykłego A-6b i pominięcie tego, że ruch z prawej ma tutaj uporządkowany, jednokierunkowy charakter.',
                'faq_preparation' => 'Na wlot drogi jednokierunkowej z prawej oraz na możliwość pojawienia się tam ruchu w sposób bardziej dynamiczny i przewidywalny kierunkowo.',
                'faq_mistake' => 'Kierowcy często czytają znak zbyt ogólnie i nie wykorzystują informacji, że ruch nadjedzie wyłącznie z jednego kierunku.',
                'editorial_notes' => 'W przyszłości warto zestawić z A-6e i z materiałem o różnicach względem zwykłych wlotów podporządkowanych.',
            ],
            'A-6e' => [
                'hazard' => 'wlotem drogi jednokierunkowej z lewej strony',
                'meaning' => 'To ostrzeżenie o wlocie drogi jednokierunkowej z lewej. Kierowca powinien wcześniej przygotować obserwację tej relacji i rozumieć, z którego kierunku może pojawić się pojazd.',
                'placement' => 'Najczęściej znak pojawia się tam, gdzie sama geometria skrzyżowania nie podpowiada od razu, że z lewej dochodzi droga o ruchu jednokierunkowym.',
                'behavior' => 'Zwolnij wcześniej i kontroluj lewą stronę skrzyżowania tak, by nie odkryć tego wlotu dopiero w ostatniej chwili.',
                'mistake' => 'Typowy błąd to czytanie znaku jak zwykłego lewego wlotu podporządkowanego bez uwzględnienia specyfiki ruchu jednokierunkowego.',
                'faq_preparation' => 'Na lewy wlot drogi jednokierunkowej i na możliwość nadjechania pojazdu z precyzyjnie określonego kierunku.',
                'faq_mistake' => 'Najczęściej kierowcy zbyt późno rozpoznają układ skrzyżowania i przez to nie przygotowują obserwacji pod właściwy kierunek ruchu.',
                'editorial_notes' => 'Utrzymywać blisko A-6d w późniejszym rolloucie.',
            ],
            'A-7' => [
                'hazard' => 'miejscem, w którym kierowca będzie musiał ustąpić pierwszeństwa',
                'meaning' => 'To ostrzeżenie o konieczności podporządkowania się ruchowi na drodze z pierwszeństwem. W praktyce kierowca ma odpowiednio wcześnie przygotować obserwację relacji pierwszeństwa i tempo dojazdu do skrzyżowania.',
                'placement' => 'Najczęściej występuje przed skrzyżowaniami dróg podporządkowanych, wyjazdami z dróg lokalnych i miejscami o niejednoznacznej geometrii pierwszeństwa.',
                'behavior' => 'Zwolnij wcześniej, szukaj relacji ruchu na drodze z pierwszeństwem i przygotuj się do zatrzymania, jeśli sytuacja tego wymaga.',
                'mistake' => 'Najczęstszy błąd to zbyt późna obserwacja drogi z pierwszeństwem i próba oceny sytuacji dopiero przy samej krawędzi jezdni.',
                'faq_preparation' => 'Na ocenę pierwszeństwa przejazdu i na możliwość pełnego zatrzymania przed wjazdem w strefę kolizji.',
                'faq_mistake' => 'Kierowcy często dojeżdżają za szybko i dopiero na końcu próbują ocenić ruch z obu stron.',
                'editorial_notes' => 'Publiczna strona już istnieje; ten wpis trzymamy tylko jako kompletność katalogu buildera.',
            ],
            'A-8' => [
                'hazard' => 'skrzyżowaniem o ruchu okrężnym',
                'meaning' => 'Znak uprzedza, że za chwilę kierowca wjedzie w układ ronda. Trzeba wcześniej przygotować obserwację ruchu na obwiedni i dostosować prędkość do sposobu wjazdu na skrzyżowanie.',
                'placement' => 'Najczęściej stoi przed rondami, zwłaszcza tam, gdzie kierowca dojeżdża do nich z odcinka o wyższej prędkości lub słabszej czytelności otoczenia.',
                'behavior' => 'Odejmij gaz wcześniej, obserwuj ruch z lewej strony i nie zostawiaj decyzji o wjeździe na rondo na ostatnią chwilę.',
                'mistake' => 'Częsty błąd to potraktowanie ronda jak zwykłego skrzyżowania i zbyt późne przeniesienie uwagi na ruch już poruszający się po obwiedni.',
                'faq_preparation' => 'Na wjazd do ruchu okrężnego, który wymaga wcześniejszego zwolnienia i ustawienia obserwacji pod pojazdy już jadące po rondzie.',
                'faq_mistake' => 'Najczęściej kierowca za długo patrzy tylko na własny pas dojazdowy i zbyt późno ocenia sytuację na rondzie.',
                'editorial_notes' => 'Mocny kandydat do pierwszego warning rolloutu po A-5 i rodzinie A-6.',
            ],
            'A-9' => [
                'hazard' => 'przejazdem kolejowym z zaporami',
                'meaning' => 'Znak ostrzega o zbliżaniu się do przejazdu kolejowego wyposażonego w zapory lub półzapory. Kierowca powinien wcześniej ustawić obserwację na sygnalizację, zapory i sytuację na torach.',
                'placement' => 'Najczęściej poprzedza przejazdy kolejowe, na których sam widok torów może pojawić się dopiero bliżej miejsca przecinania drogi z linią kolejową.',
                'behavior' => 'Zmniejsz prędkość, obserwuj sygnalizację i zapory oraz nie dojeżdżaj do przejazdu z założeniem, że jeśli nic nie widać z daleka, przejazd będzie na pewno wolny.',
                'mistake' => 'Najczęstszy błąd to traktowanie przejazdu z zaporami jako miejsca, które \"samo się zabezpieczy\", i przez to zbyt późne ograniczenie prędkości.',
                'faq_preparation' => 'Na przejazd kolejowy, sygnalizację i możliwość nagłej zmiany sytuacji przy zaporach.',
                'faq_mistake' => 'Najczęściej problemem jest przecenienie roli samych zapór i niedostateczne przygotowanie prędkości przed dojazdem do przejazdu.',
                'editorial_notes' => 'W przyszłości połączyć z A-10 i z materiałem o czytaniu oznakowania przejazdów kolejowych.',
            ],
            'A-10' => [
                'hazard' => 'przejazdem kolejowym bez zapór',
                'meaning' => 'To ostrzeżenie o przejeździe kolejowym bez fizycznych zapór. Kierowca powinien podejść do niego z większym zapasem obserwacji i kontroli prędkości niż do zwykłego skrzyżowania.',
                'placement' => 'Najczęściej stoi przed przejazdami, na których ochrona nie opiera się na zaporach, a bezpieczeństwo w dużym stopniu zależy od właściwej obserwacji i decyzji kierowcy.',
                'behavior' => 'Wytracaj prędkość wcześniej, patrz daleko wzdłuż torów i nie przyjmuj, że brak zapór oznacza prostszy albo mniej wymagający przejazd.',
                'mistake' => 'Najczęstszy błąd to dojazd zbyt szybko i traktowanie przejazdu bez zapór jak zwykłego przecięcia drogi, bez pełnego przygotowania obserwacji torów.',
                'faq_preparation' => 'Na przejazd kolejowy wymagający bardzo świadomej obserwacji torów i sygnalizacji bez wsparcia fizycznych zapór.',
                'faq_mistake' => 'Kierowcy zbyt często odkładają ocenę sytuacji na torach do ostatniego momentu.',
                'editorial_notes' => 'Dobrze zestawić później z A-9.',
            ],
            'A-11' => [
                'hazard' => 'nierówną drogą',
                'meaning' => 'Znak uprzedza, że za chwilę nawierzchnia może pogorszyć stabilność pojazdu, wydłużyć drogę hamowania albo wybić kierowcę z rytmu prowadzenia auta.',
                'placement' => 'Najczęściej pojawia się przed odcinkami o uszkodzonej nawierzchni, wybojach lub innych nierównościach, które przy wyższej prędkości stają się istotnym zagrożeniem.',
                'behavior' => 'Zwolnij przed wjazdem na nierówności, trzymaj pewnie kierownicę i nie wykonuj gwałtownych manewrów w momencie, gdy auto zaczyna podskakiwać lub tracić stabilność.',
                'mistake' => 'Typowy błąd to brak redukcji prędkości i wejście na nierówności z tempem dobranym do gładkiej nawierzchni.',
                'faq_preparation' => 'Na pogorszenie jakości nawierzchni, które może zmienić zachowanie auta przy hamowaniu i prowadzeniu.',
                'faq_mistake' => 'Najczęściej kierowca za późno redukuje prędkość i dopiero na nierównościach próbuje ratować komfort oraz stabilność jazdy.',
                'editorial_notes' => 'Można później połączyć z A-11a i A-15.',
            ],
            'A-11a' => [
                'hazard' => 'progiem zwalniającym',
                'meaning' => 'Znak ostrzega o urządzeniu wymuszającym spadek prędkości. Kierowca powinien odpowiednio wcześnie wytracić tempo, żeby przejechać próg płynnie i bez przeciążania pojazdu.',
                'placement' => 'Najczęściej stoi na odcinkach uspokojonego ruchu, przy szkołach, przejściach i w strefach, gdzie zarządca drogi chce wymusić bardzo wyraźne obniżenie prędkości.',
                'behavior' => 'Hamuj przed progiem, nie na samym progu. Podejdź do niego z prędkością pozwalającą przejechać bez szarpnięcia i bez utraty kontroli nad autem.',
                'mistake' => 'Najczęstszy błąd to późne hamowanie i wjeżdżanie na próg z prędkością większą, niż pozwala na to geometria urządzenia.',
                'faq_preparation' => 'Na fizyczne urządzenie w jezdni, które wymaga wcześniejszego wytracenia prędkości.',
                'faq_mistake' => 'Najczęściej kierowca hamuje dopiero przy samym progu i przenosi obciążenie auta w niewłaściwym momencie.',
                'editorial_notes' => 'Dobry znak do późniejszego materiału praktycznego o jeździe w strefach uspokojonych.',
            ],
            'A-12a' => [
                'hazard' => 'dwustronnym zwężeniem jezdni',
                'meaning' => 'Znak uprzedza, że szerokość jezdni zmniejszy się po obu stronach. To wymaga wcześniejszego ustawienia toru jazdy i większej uwagi wobec pojazdów z naprzeciwka lub obok.',
                'placement' => 'Najczęściej stoi przed remontami, przewężeniami mostowymi, wlotami do węższej jezdni i miejscami, w których zapas boczny wyraźnie maleje.',
                'behavior' => 'Ogranicz prędkość, ustaw pojazd centralnie i nie zostawiaj oceny szerokości pasa na ostatni moment.',
                'mistake' => 'Częsty błąd to późne zauważenie zwężenia i wejście w nie z prędkością, która nie daje już komfortu na korektę toru jazdy.',
                'faq_preparation' => 'Na przewężenie, przy którym zmniejsza się margines bezpieczeństwa po obu stronach jezdni.',
                'faq_mistake' => 'Najczęściej kierowca zbyt późno dostosowuje pozycję auta i prędkość do nowej szerokości jezdni.',
                'editorial_notes' => 'Powiązać z A-12b i A-12c.',
            ],
            'A-12b' => [
                'hazard' => 'prawostronnym zwężeniem jezdni',
                'meaning' => 'To ostrzeżenie, że prawa krawędź jezdni za chwilę się zbliży. Kierowca powinien wcześniej ustawić tor jazdy i uwzględnić ograniczony zapas boczny po prawej stronie.',
                'placement' => 'Najczęściej występuje przed remontami, przewężeniami mostowymi lub miejscami, gdzie infrastruktura ogranicza prawą część jezdni.',
                'behavior' => 'Zwolnij, patrz szeroko na prawą krawędź jezdni i nie dopuszczaj do sytuacji, w której korekta toru jazdy musi być gwałtowna.',
                'mistake' => 'Najczęstszy błąd to zbyt późne zauważenie, że zwężenie dotyczy właśnie prawej strony, i zostawienie sobie za małego marginesu bocznego.',
                'faq_preparation' => 'Na zmniejszenie przestrzeni po prawej stronie pasa ruchu.',
                'faq_mistake' => 'Kierowca często nie ustawia auta odpowiednio wcześnie i dopiero w samym przewężeniu zaczyna poprawiać tor jazdy.',
                'editorial_notes' => 'Trzymać razem z A-12a i A-12c.',
            ],
            'A-12c' => [
                'hazard' => 'lewostronnym zwężeniem jezdni',
                'meaning' => 'Znak ostrzega, że lewa strona jezdni będzie ograniczona i wymusi wcześniejsze uporządkowanie toru jazdy oraz obserwacji otoczenia.',
                'placement' => 'Najczęściej pojawia się tam, gdzie przewężenie dotyczy lewej krawędzi jezdni, np. przy remontach lub zmianach geometrii drogi.',
                'behavior' => 'Dostosuj prędkość i ustawienie auta z wyprzedzeniem tak, żeby nie wykonywać nerwowej korekty dopiero w przewężeniu.',
                'mistake' => 'Najczęstszy błąd to skupienie uwagi tylko na jezdni przed sobą i zbyt późne zauważenie, że realnie maleje przestrzeń po lewej stronie.',
                'faq_preparation' => 'Na ograniczenie szerokości jezdni od lewej strony i konieczność wcześniejszego ustawienia auta.',
                'faq_mistake' => 'Kierowcy często zostawiają korektę położenia auta na sam koniec zamiast przygotować ją z wyprzedzeniem.',
                'editorial_notes' => 'Połączyć w klaster ze zwężeniami A-12.',
            ],
            'A-13' => [
                'hazard' => 'ruchomym mostem',
                'meaning' => 'To ostrzeżenie, że za chwilę droga przecina obiekt, którego ruch lub sposób działania może okresowo zmieniać warunki przejazdu.',
                'placement' => 'Najczęściej stoi przed mostami zwodzonymi lub innymi ruchomymi konstrukcjami, przy których kierowca musi liczyć się z czasowym wstrzymaniem ruchu i zmianą sygnalizacji.',
                'behavior' => 'Zwolnij, obserwuj sygnalizację i otoczenie obiektu oraz nie zakładaj, że przejazd będzie zawsze dostępny bez zatrzymania.',
                'mistake' => 'Częsty błąd to potraktowanie znaku wyłącznie jako ciekawostki technicznej i brak przygotowania na sterowanie ruchem przy obiekcie.',
                'faq_preparation' => 'Na obiekt, przy którym organizacja ruchu może chwilowo się zmieniać ze względu na działanie mostu.',
                'faq_mistake' => 'Najczęściej kierowca nie przygotowuje się na sygnalizację lub możliwe zatrzymanie przed obiektem.',
                'editorial_notes' => 'Niszowy, ale ważny dla kompletności pełnego katalogu.',
            ],
            'A-14' => [
                'hazard' => 'robotami na drodze',
                'meaning' => 'Znak uprzedza o odcinku, na którym organizacja ruchu, szerokość pasa, przyczepność albo tor jazdy mogą być czasowo zmienione przez prace drogowe.',
                'placement' => 'Najczęściej występuje przed zwężeniami, objazdami, zmianami toru jazdy i miejscami, gdzie pracownicy lub sprzęt drogowy wchodzą w bezpośredni kontakt z ruchem.',
                'behavior' => 'Odejmij gaz wcześniej, patrz na znaki tymczasowe i nie prowadź auta tak, jakby obowiązywała zwykła geometria odcinka sprzed robót.',
                'mistake' => 'Najczęstszy błąd to zauważenie samego A-14, ale zignorowanie całej dalszej sekwencji oznakowania tymczasowego.',
                'faq_preparation' => 'Na czasową zmianę organizacji ruchu, zwężenia, pracowników na drodze i niestandardowy przebieg pasa.',
                'faq_mistake' => 'Kierowcy często patrzą tylko na pierwszy znak i nie czytają dalszych tablic oraz oznakowania prowadzącego.',
                'editorial_notes' => 'To mocna strona użytkowa; przy późniejszym rolloucie warto dodać konkretne scenariusze robót.',
            ],
            'A-15' => [
                'hazard' => 'śliską jezdnią',
                'meaning' => 'To ostrzeżenie, że przyczepność nawierzchni za chwilę może być wyraźnie gorsza niż na poprzednim odcinku. Kierowca powinien wcześniej uspokoić jazdę i unikać gwałtownych ruchów.',
                'placement' => 'Najczęściej pojawia się przed odcinkami narażonymi na wodę, błoto, zanieczyszczenia lub inne warunki obniżające przyczepność.',
                'behavior' => 'Wytracaj prędkość płynnie, nie wykonuj agresywnych manewrów kierownicą ani pedałami i zostaw sobie większy zapas na hamowanie.',
                'mistake' => 'Najczęstszy błąd to jazda tempem dobranym do suchej nawierzchni mimo wyraźnego ostrzeżenia o pogorszonej przyczepności.',
                'faq_preparation' => 'Na odcinek, na którym koła mogą szybciej tracić przyczepność przy hamowaniu i skręcaniu.',
                'faq_mistake' => 'Najczęściej kierowca redukuje prędkość za późno albo wykonuje zbyt gwałtowne ruchy już na śliskiej nawierzchni.',
                'editorial_notes' => 'Warto później połączyć z A-32 i zimowym klastrem świeżości.',
            ],
            'A-16' => [
                'hazard' => 'przejściem dla pieszych',
                'meaning' => 'Znak ostrzega, że za chwilę kierowca zbliży się do przejścia dla pieszych i musi wcześniej przygotować obserwację nie tylko jezdni, ale też chodnika i pobocza.',
                'placement' => 'Najczęściej stoi przed przejściami, które wymagają wcześniejszego ostrzeżenia, zwłaszcza na szybszych odcinkach lub tam, gdzie pieszy może pojawić się nagle.',
                'behavior' => 'Zwolnij wcześniej, patrz na krawędź chodnika, wyspy i okolice przejścia oraz przygotuj nogę do natychmiastowej reakcji.',
                'mistake' => 'Najczęstszy błąd to obserwowanie wyłącznie pasów na jezdni bez szukania pieszego, który dopiero zbliża się do przejścia.',
                'faq_preparation' => 'Na przejście dla pieszych i na możliwość nagłej zmiany sytuacji przez wchodzącego pieszego.',
                'faq_mistake' => 'Kierowca często patrzy tylko na samo oznakowanie przejścia, a za mało na ludzi w jego otoczeniu.',
                'editorial_notes' => 'Mocny kandydat do pierwszego publicznego rolloutu warning signs.',
            ],
            'A-17' => [
                'hazard' => 'miejscem, w którym można spodziewać się obecności dzieci',
                'meaning' => 'To ostrzeżenie o strefie, gdzie zachowanie pieszych może być mniej przewidywalne. Kierowca powinien wcześniej ograniczyć prędkość i poszerzyć obserwację otoczenia.',
                'placement' => 'Najczęściej stoi przy szkołach, przedszkolach, przejściach w pobliżu osiedli i innych miejscach o zwiększonej obecności dzieci.',
                'behavior' => 'Zmniejsz prędkość, patrz szeroko na chodnik i pobocze oraz zostaw sobie zapas na nagłą reakcję dziecka.',
                'mistake' => 'Częsty błąd to zauważenie znaku bez realnej zmiany stylu jazdy i bez szukania źródła potencjalnego wtargnięcia na jezdnię.',
                'faq_preparation' => 'Na obecność dzieci w pobliżu jezdni i na konieczność bardzo wczesnej gotowości do hamowania.',
                'faq_mistake' => 'Najczęściej kierowca patrzy za wąsko i nie zostawia sobie rezerwy na nagłą reakcję pieszego.',
                'editorial_notes' => 'Publiczna strona już istnieje; wpis zostaje dla kompletności katalogu.',
            ],
            'A-18a' => [
                'hazard' => 'miejscem, w którym na drogę mogą wejść zwierzęta gospodarskie',
                'meaning' => 'Znak ostrzega o możliwości pojawienia się na jezdni zwierząt gospodarskich. Kierowca powinien wcześniej zmniejszyć prędkość i liczyć się z wolnym, niestandardowym ruchem.',
                'placement' => 'Najczęściej występuje przy terenach wiejskich, pastwiskach i miejscach przepędu zwierząt przez drogę.',
                'behavior' => 'Zwolnij i obserwuj pobocze szeroko. Jeśli zwierzęta już są blisko jezdni, przygotuj się na pełne zatrzymanie, a nie tylko lekkie odjęcie gazu.',
                'mistake' => 'Najczęstszy błąd to potraktowanie znaku jako rzadkiej ciekawostki i brak realnej gotowości na bardzo wolny lub chaotyczny ruch zwierząt.',
                'faq_preparation' => 'Na obecność zwierząt gospodarskich, które mogą wejść na jezdnię i poruszać się wolno lub nieprzewidywalnie.',
                'faq_mistake' => 'Kierowcy zbyt często nie redukują prędkości, bo zakładają, że zagrożenie i tak się nie pojawi.',
                'editorial_notes' => 'Dobrze spiąć z A-18b.',
            ],
            'A-18b' => [
                'hazard' => 'miejscem, w którym na drogę mogą wejść zwierzęta dzikie',
                'meaning' => 'To ostrzeżenie o odcinku, na którym zwierzęta dzikie mogą pojawić się nagle i w trudnym do przewidzenia momencie. Kierowca ma wcześniej przygotować prędkość i zakres obserwacji.',
                'placement' => 'Najczęściej stoi w pobliżu lasów, korytarzy migracyjnych i odcinków, na których regularnie dochodzi do wtargnięć zwierzyny.',
                'behavior' => 'Ogranicz prędkość, obserwuj pobocze i ciemne strefy przy drodze oraz zostaw sobie zapas na natychmiastową reakcję.',
                'mistake' => 'Najczęstszy błąd to jazda ze stałą prędkością mimo ostrzeżenia i przecenianie własnej możliwości reakcji przy nagłym wtargnięciu zwierzęcia.',
                'faq_preparation' => 'Na nagłe wtargnięcie zwierzyny, zwłaszcza na odcinkach z ograniczoną widocznością po bokach drogi.',
                'faq_mistake' => 'Kierowca często ignoruje znak, jeśli akurat nie widzi zwierząt w pobliżu jezdni.',
                'editorial_notes' => 'Silny kandydat do treści sezonowej i świeżościowej.',
            ],
            'A-19' => [
                'hazard' => 'bocznym wiatrem',
                'meaning' => 'Znak uprzedza, że na najbliższym odcinku podmuchy boczne mogą wpływać na tor jazdy pojazdu, szczególnie lżejszego albo o większej powierzchni bocznej.',
                'placement' => 'Najczęściej pojawia się na mostach, estakadach, otwartych przestrzeniach i wyniesionych odcinkach drogi bardziej wystawionych na wiatr.',
                'behavior' => 'Trzymaj auto stabilnie, ogranicz prędkość i nie wykonuj gwałtownych ruchów kierownicą. Zostaw też większy margines względem innych pojazdów.',
                'mistake' => 'Częsty błąd to niedocenienie wpływu wiatru na tor jazdy, zwłaszcza przy wyjeździe z osłoniętego odcinka na otwartą przestrzeń.',
                'faq_preparation' => 'Na podmuchy wiatru, które mogą przestawiać auto na pasie ruchu albo destabilizować prowadzenie.',
                'faq_mistake' => 'Najczęściej problemem jest utrzymywanie zbyt dużej prędkości i zbyt małego marginesu na korektę toru jazdy.',
                'editorial_notes' => 'Warto później połączyć z warunkami pogodowymi i A-32.',
            ],
            'A-20' => [
                'hazard' => 'odcinkiem jezdni o ruchu dwukierunkowym',
                'meaning' => 'Znak ostrzega, że kierowca wjeżdża na odcinek, na którym pojazdy nadjadą także z przeciwka. To wymaga zmiany przyzwyczajeń po wcześniejszym ruchu jednokierunkowym lub rozdzielonym.',
                'placement' => 'Najczęściej stoi tam, gdzie kończy się jezdnia jednokierunkowa albo zmienia się organizacja ruchu z rozdzielonej na wspólną.',
                'behavior' => 'Wcześniej zwolnij, wróć myśleniem do pełnej obserwacji przeciwnego kierunku i nie ustawiaj auta tak, jakbyś nadal jechał po odcinku bez ruchu z naprzeciwka.',
                'mistake' => 'Najczęstszy błąd to zbyt późne przełączenie uwagi na pojazdy jadące z przeciwka i utrzymywanie pozycji lub prędkości typowej dla ruchu jednokierunkowego.',
                'faq_preparation' => 'Na powrót ruchu z przeciwka i na mniejszy margines błędu przy wyprzedzaniu lub ustawieniu toru jazdy.',
                'faq_mistake' => 'Kierowca często za długo zachowuje nawyki z poprzedniego odcinka i za mało miejsca zostawia względem osi jezdni.',
                'editorial_notes' => 'Dobry materiał porównawczy z B-31 w przyszłości.',
            ],
            'A-21' => [
                'hazard' => 'miejscem, w którym może pojawić się tramwaj',
                'meaning' => 'To ostrzeżenie o przecięciu relacji ruchu drogowego z ruchem tramwajowym. Kierowca powinien wcześniej poszerzyć obserwację i przygotować się na pojazd szynowy o innym torze ruchu niż auta.',
                'placement' => 'Najczęściej pojawia się w pobliżu torowisk przecinających jezdnię lub odcinków, gdzie tramwaj wchodzi w relację z ruchem drogowym.',
                'behavior' => 'Ogranicz prędkość, sprawdzaj nie tylko auta, ale też torowisko i sygnalizację. Tramwaj bywa cichszy lub szybszy, niż kierowca zakłada przy pobieżnej obserwacji.',
                'mistake' => 'Najczęstszy błąd to traktowanie miejsca jak zwykłego skrzyżowania bez uwzględnienia osobnego toru i dynamiki ruchu tramwaju.',
                'faq_preparation' => 'Na możliwość przecięcia lub współistnienia z ruchem tramwajowym.',
                'faq_mistake' => 'Kierowcy zbyt często obserwują wyłącznie jezdnię dla aut i ignorują torowisko.',
                'editorial_notes' => 'Dobra strona do późniejszego rozwinięcia o relacje z pierwszeństwem na torowisku.',
            ],
            'A-22' => [
                'hazard' => 'niebezpiecznym zjazdem',
                'meaning' => 'Znak uprzedza o zjeździe, na którym sama geometria odcinka może szybko zwiększyć prędkość pojazdu i utrudnić kontrolę nad tempem jazdy.',
                'placement' => 'Najczęściej stoi przed dłuższymi lub bardziej stromymi spadkami terenu, gdzie utrzymanie bezpiecznej prędkości wymaga wcześniejszej decyzji kierowcy.',
                'behavior' => 'Zredukuj prędkość jeszcze przed zjazdem, a nie dopiero w jego połowie. W razie potrzeby dobierz bieg tak, żeby auto nie zaczęło samoistnie przyspieszać.',
                'mistake' => 'Najczęstszy błąd to wjazd na zjazd z tempem dobranym do prostej i próba korygowania prędkości dopiero po nabraniu rozpędu.',
                'faq_preparation' => 'Na odcinek, na którym prędkość może narastać szybciej niż zwykle z powodu spadku terenu.',
                'faq_mistake' => 'Kierowca często zostawia decyzję o redukcji prędkości na zbyt późny moment.',
                'editorial_notes' => 'Później połączyć z A-23.',
            ],
            'A-23' => [
                'hazard' => 'stromym podjazdem',
                'meaning' => 'To ostrzeżenie o odcinku, na którym warunki jazdy zmienią się przez wyraźny podjazd. Kierowca powinien wcześniej ustawić prędkość i przygotować auto do stabilnego pokonania wzniesienia.',
                'placement' => 'Najczęściej występuje przed stromymi podjazdami, gdzie utrzymanie płynności jazdy lub widoczności wymaga wcześniejszej decyzji.',
                'behavior' => 'Zadbaj o odpowiednią prędkość jeszcze przed początkiem wzniesienia i zwróć uwagę na ograniczenie widoczności za szczytem podjazdu.',
                'mistake' => 'Częsty błąd to patrzenie wyłącznie na tempo jazdy bez uwzględnienia tego, że za szczytem widoczność może być mocno ograniczona.',
                'faq_preparation' => 'Na podjazd zmieniający dynamikę auta i często ograniczający widoczność w dalszej części odcinka.',
                'faq_mistake' => 'Najczęściej kierowca za mało myśli o widoczności za wzniesieniem i o potrzebie wcześniejszego przygotowania auta.',
                'editorial_notes' => 'Powiązać z A-22.',
            ],
            'A-24' => [
                'hazard' => 'miejscem, w którym mogą pojawić się rowerzyści',
                'meaning' => 'Znak ostrzega o relacji z ruchem rowerowym. Kierowca powinien wcześniej przygotować obserwację pobocza, pasa rowerowego, przejazdu dla rowerów albo strefy wjazdu rowerzystów do ruchu.',
                'placement' => 'Najczęściej występuje w pobliżu przejazdów rowerowych, dróg dla rowerów i odcinków, gdzie rowerzyści włączają się do ruchu lub przecinają tor jazdy samochodów.',
                'behavior' => 'Zwolnij, patrz szeroko po bokach jezdni i nie zakładaj, że rowerzysta będzie poruszał się z tempem pozwalającym na bardzo późną reakcję kierowcy.',
                'mistake' => 'Najczęstszy błąd to niedoszacowanie prędkości rowerzysty i zbyt późne zauważenie momentu, w którym przecina on tor jazdy auta.',
                'faq_preparation' => 'Na obecność rowerzystów w pobliżu jezdni, przejazdu rowerowego albo relacji włączania się do ruchu.',
                'faq_mistake' => 'Kierowca często zauważa rowerzystę za późno albo błędnie ocenia jego tempo dojazdu do punktu kolizji.',
                'editorial_notes' => 'Mocny kandydat do pierwszego warning rolloutu.',
            ],
            'A-25' => [
                'hazard' => 'spadającymi odłamkami skalnymi',
                'meaning' => 'Znak ostrzega o odcinku, na którym naturalne ukształtowanie terenu może powodować spadanie odłamków na jezdnię. Kierowca powinien zwolnić i obserwować nie tylko samą drogę, ale też stok lub skarpę.',
                'placement' => 'Najczęściej stoi na drogach górskich i w miejscach biegnących pod stromymi skarpami lub ścianami skalnymi.',
                'behavior' => 'Ogranicz prędkość i nie jedź mechanicznie „środkiem kadru”. Obserwuj też pobocze, skarpę i ewentualne zanieczyszczenia na jezdni.',
                'mistake' => 'Najczęstszy błąd to zbyt wąska obserwacja ograniczona do pasa ruchu, bez szukania śladów osuwania lub kamieni przy krawędzi jezdni.',
                'faq_preparation' => 'Na możliwe odłamki lub zanieczyszczenia pojawiające się na jezdni z terenu przyległego.',
                'faq_mistake' => 'Kierowca często nie poszerza obserwacji poza sam asfalt i przez to za późno reaguje na realne zagrożenie.',
                'editorial_notes' => 'Niszowy, ale dobry materiał ekspercki dla kompletności.',
            ],
            'A-26' => [
                'hazard' => 'lotniskiem lub ruchem statków powietrznych w pobliżu drogi',
                'meaning' => 'To ostrzeżenie o odcinku, gdzie ruch lotniczy, hałas lub specyficzne otoczenie mogą wpływać na uwagę kierowcy. Znak przypomina, że warunki w pobliżu lotniska bywają nietypowe.',
                'placement' => 'Najczęściej występuje na drogach przebiegających blisko lotnisk lub w strefach, gdzie niski przelot statków powietrznych może rozpraszać uczestników ruchu.',
                'behavior' => 'Zachowaj pełną koncentrację na drodze i nie pozwól, by bodźce z otoczenia odciągały uwagę od prowadzenia auta.',
                'mistake' => 'Najczęstszy błąd to potraktowanie znaku jako ciekawostki i niedocenienie wpływu rozproszenia uwagi na bezpieczeństwo jazdy.',
                'faq_preparation' => 'Na niestandardowe otoczenie drogi i bodźce, które mogą rozpraszać kierowcę.',
                'faq_mistake' => 'Kierowca nie docenia ryzyka rozproszenia i za mało pilnuje podstawowej obserwacji drogi.',
                'editorial_notes' => 'Krótki, rzeczowy wpis; nie rozdmuchiwać ponad realną wartość użytkową.',
            ],
            'A-27' => [
                'hazard' => 'nabrzeżem lub brzegiem rzeki',
                'meaning' => 'Znak uprzedza, że droga biegnie w bezpośredniej bliskości wody lub jej krawędzi. Kierowca powinien wcześniej ustawić prędkość i tor jazdy z większym marginesem bezpieczeństwa.',
                'placement' => 'Najczęściej stoi na drogach przylegających do rzek, kanałów, nabrzeży lub innych akwenów, gdzie wyjechanie poza jezdnię może mieć szczególnie groźne skutki.',
                'behavior' => 'Zwolnij, prowadź płynnie i nie zostawiaj sobie minimalnego marginesu od krawędzi jezdni czy pobocza.',
                'mistake' => 'Częsty błąd to jazda z tempem dobranym do zwykłego odcinka drogi mimo znacznie większej wagi ewentualnego wyjechania poza jezdnię.',
                'faq_preparation' => 'Na odcinek z małym marginesem błędu względem wody lub skarpy przy drodze.',
                'faq_mistake' => 'Najczęściej kierowca nie redukuje prędkości mimo większej konsekwencji ewentualnej pomyłki toru jazdy.',
                'editorial_notes' => 'Może być powiązane z A-22, A-25 i drogami o podwyższonym ryzyku terenowym.',
            ],
            'A-28' => [
                'hazard' => 'sypkim żwirem',
                'meaning' => 'To ostrzeżenie o nawierzchni lub fragmencie drogi, na którym luźny materiał może pogorszyć przyczepność i wydłużyć drogę hamowania.',
                'placement' => 'Najczęściej występuje na odcinkach świeżo utrzymanych, remontowanych albo lokalnie zanieczyszczonych sypkim materiałem.',
                'behavior' => 'Zmniejsz prędkość, unikaj gwałtownego hamowania i ostrych ruchów kierownicą oraz zostaw większy dystans do pojazdu przed sobą.',
                'mistake' => 'Najczęstszy błąd to jazda tak, jakby nawierzchnia wciąż dawała tę samą przyczepność co asfalt bez luźnej warstwy na wierzchu.',
                'faq_preparation' => 'Na pogorszenie przyczepności przez luźny materiał zalegający na jezdni.',
                'faq_mistake' => 'Kierowca często zbyt długo utrzymuje zwykłą prędkość i dopiero przy hamowaniu odkrywa, że nawierzchnia zachowuje się inaczej.',
                'editorial_notes' => 'Dobrze później połączyć z A-15.',
            ],
            'A-29' => [
                'hazard' => 'sygnałami świetlnymi',
                'meaning' => 'Znak ostrzega, że za chwilę kierowca dojedzie do sygnalizacji świetlnej i powinien wcześniej przygotować obserwację pod zmianę wskazań oraz zachowanie innych uczestników ruchu.',
                'placement' => 'Najczęściej stoi przed sygnalizacją, która pojawia się po szybszym odcinku drogi albo w miejscu, gdzie nie jest dobrze widoczna z dużej odległości.',
                'behavior' => 'Ogranicz prędkość i nie zakładaj, że zielone światło utrzyma się do Twojego dojazdu. Przygotuj się zarówno na zatrzymanie, jak i na reakcje innych kierowców.',
                'mistake' => 'Najczęstszy błąd to dojazd „na pamięć”, bez realnej gotowości na zmianę sygnału w chwili zbliżania się do skrzyżowania.',
                'faq_preparation' => 'Na sygnalizację świetlną i na możliwość szybkiej zmiany sytuacji w strefie zatrzymania.',
                'faq_mistake' => 'Kierowcy często dojeżdżają za szybko do sygnalizacji, zakładając, że obecny sygnał utrzyma się bez zmian.',
                'editorial_notes' => 'Silny kandydat do pierwszego publicznego rolloutu warning signs.',
            ],
            'A-30' => [
                'hazard' => 'innym niebezpieczeństwem wymagającym doprecyzowania przez organizację ruchu',
                'meaning' => 'To najbardziej ogólny znak ostrzegawczy w tej grupie. Sam nie opisuje dokładnego zagrożenia, dlatego kierowca musi czytać go razem z tabliczką lub kontekstem miejsca.',
                'placement' => 'Najczęściej pojawia się tam, gdzie potrzebne jest ostrzeżenie przed nietypowym zagrożeniem niewchodzącym wprost w katalog bardziej szczegółowych znaków A.',
                'behavior' => 'Po minięciu znaku od razu szukaj informacji doprecyzowującej i nie zakładaj, że skoro nie rozpoznajesz zagrożenia z daleka, możesz jechać bez zmiany zachowania.',
                'mistake' => 'Najczęstszy błąd to zignorowanie potrzeby odczytania tabliczki lub kontekstu, który tłumaczy, przed czym dokładnie znak ostrzega.',
                'faq_preparation' => 'Na nietypowe zagrożenie, którego szczegóły trzeba odczytać z oznakowania dodatkowego lub z samego miejsca.',
                'faq_mistake' => 'Kierowca często patrzy na sam trójkąt ostrzegawczy i nie czyta tego, co doprecyzowuje znaczenie znaku.',
                'editorial_notes' => 'Przed publikacją koniecznie dodać przykłady z tabliczkami i kontekstem użycia.',
            ],
            'A-31' => [
                'hazard' => 'niebezpiecznym poboczem',
                'meaning' => 'Znak uprzedza, że pobocze na najbliższym odcinku może nie nadawać się do bezpiecznego najechania albo awaryjnego zjazdu. Kierowca powinien prowadzić auto z większym zapasem względem krawędzi jezdni.',
                'placement' => 'Najczęściej występuje tam, gdzie pobocze jest niestabilne, miękkie lub uskokowe i nie daje typowego wsparcia w sytuacji awaryjnej.',
                'behavior' => 'Trzymaj wyraźny margines od krawędzi jezdni, nie ścinaj toru jazdy i nie zakładaj, że w razie problemu można bezpiecznie uciec na pobocze.',
                'mistake' => 'Najczęstszy błąd to zbyt bliskie prowadzenie pojazdu przy krawędzi drogi mimo wyraźnego ostrzeżenia o niebezpiecznym poboczu.',
                'faq_preparation' => 'Na pobocze, które nie daje zwykłego marginesu bezpieczeństwa przy zjeździe z pasa.',
                'faq_mistake' => 'Kierowca często traktuje pobocze jak normalną strefę rezerwy, choć znak ostrzega, że może ono być zdradliwe.',
                'editorial_notes' => 'Dobrze spiąć z A-11 i A-28.',
            ],
            'A-32' => [
                'hazard' => 'oszronieniem jezdni',
                'meaning' => 'To ostrzeżenie o odcinku, na którym nawierzchnia może ulec oszronieniu szybciej niż na sąsiednich fragmentach drogi. Wymaga to wcześniejszego uspokojenia jazdy i większego zapasu.',
                'placement' => 'Najczęściej pojawia się w miejscach zacienionych, nad wodą, na mostach i w obniżeniach terenu, gdzie temperatura nawierzchni spada szybciej.',
                'behavior' => 'Zwolnij wcześniej, unikaj gwałtownych manewrów i traktuj ten odcinek jak potencjalnie śliski nawet wtedy, gdy poprzedni fragment drogi wydawał się suchy.',
                'mistake' => 'Najczęstszy błąd to przenoszenie wrażeń z suchej jezdni sprzed chwili na odcinek, który może mieć zupełnie inną przyczepność.',
                'faq_preparation' => 'Na lokalne pogorszenie przyczepności przez oszronienie nawierzchni.',
                'faq_mistake' => 'Kierowcy często nie redukują prędkości, bo nie widzą jeszcze gołym okiem pełnego efektu oszronienia.',
                'editorial_notes' => 'Warto powiązać z A-15 w klastrze pogodowym.',
            ],
            'A-33' => [
                'hazard' => 'zatorami drogowymi',
                'meaning' => 'Znak uprzedza, że na najbliższym odcinku kierowca może napotkać spiętrzenia ruchu i gwałtowny spadek prędkości pojazdów przed sobą.',
                'placement' => 'Najczęściej występuje na odcinkach o dużym natężeniu ruchu, przed przewężeniami lub miejscami o regularnych zatorach.',
                'behavior' => 'Patrz dalej niż zwykle, trzymaj większy odstęp i nie jedź tempem, które nie pozwala spokojnie zareagować na nagłe wyhamowanie kolumny pojazdów.',
                'mistake' => 'Najczęstszy błąd to niedocenienie szybkości, z jaką zator może „zamknąć się” przed jadącym autem.',
                'faq_preparation' => 'Na gwałtowne spowolnienie ruchu i potrzebę wczesnego odczytywania tempa kolumny pojazdów.',
                'faq_mistake' => 'Kierowcy często zostawiają zbyt mały odstęp i zbyt późno zauważają, że kolumna przed nimi wyraźnie zwalnia.',
                'editorial_notes' => 'Dobry kandydat do sezonowego freshness passu.',
            ],
            'A-34' => [
                'hazard' => 'wypadkiem drogowym lub jego skutkami na jezdni',
                'meaning' => 'Znak ostrzega o miejscu zdarzenia drogowego albo o odcinku, na którym można napotkać jego skutki. Kierowca powinien od razu przygotować się na niestandardową organizację ruchu i pracę służb.',
                'placement' => 'Najczęściej występuje czasowo w miejscach zdarzeń lub na dojazdach do odcinków, gdzie skutki wypadku wpływają na przepustowość i bezpieczeństwo ruchu.',
                'behavior' => 'Zwolnij, obserwuj polecenia służb i oznakowanie tymczasowe oraz nie próbuj jechać „normalnym rytmem”, jeśli sytuacja na drodze jest niestandardowa.',
                'mistake' => 'Najczęstszy błąd to zbyt późne ograniczenie prędkości i skupienie uwagi bardziej na samym zdarzeniu niż na bezpiecznym przeprowadzeniu własnego pojazdu przez odcinek.',
                'faq_preparation' => 'Na czasową, niestandardową sytuację na drodze związaną z wypadkiem i pracą służb.',
                'faq_mistake' => 'Kierowcy często rozpraszają się samym zdarzeniem i za mało uwagi poświęcają bezpiecznej jeździe przez ten odcinek.',
                'editorial_notes' => 'Trzymać rzeczowo; nie robić z tej strony sensacyjnego tonu.',
            ],
        ];
    }

    /**
     * @param  array{code: string, slug: string, name: string, primary_query: string}  $sign
     * @return array{hazard: string, meaning: string, placement: string, behavior: string, mistake: string, faq_preparation: string, faq_mistake: string, editorial_notes: string}
     */
    protected function fallbackConfig(array $sign): array
    {
        $lowerName = Str::of($sign['name'])->lcfirst()->toString();

        return [
            'hazard' => $lowerName,
            'meaning' => "Znak {$sign['code']} uprzedza o zagrożeniu opisanym jako {$lowerName}. Kierowca powinien odpowiednio wcześniej przygotować obserwację i zmienić styl jazdy pod warunki za znakiem.",
            'placement' => 'Najczęściej taki znak pojawia się przed miejscem, w którym zmiana warunków ruchu nie byłaby wystarczająco czytelna bez wcześniejszego ostrzeżenia.',
            'behavior' => 'Po zauważeniu znaku ogranicz prędkość, poszerz obserwację otoczenia i nie zostawiaj decyzji o reakcji na ostatni moment.',
            'mistake' => 'Najczęstszy błąd to potraktowanie znaku ostrzegawczego jak neutralnej informacji, bez realnej zmiany prędkości lub zakresu obserwacji.',
            'faq_preparation' => 'Na miejsce, które wymaga wcześniejszego przygotowania obserwacji i tempa jazdy.',
            'faq_mistake' => 'Kierowcy najczęściej reagują zbyt późno i dopiero przy samym zagrożeniu próbują skorygować prędkość lub tor jazdy.',
            'editorial_notes' => 'Przed publikacją doprecyzować przykład praktyczny i podobne znaki z tej rodziny.',
        ];
    }
}
